/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author alfredo
 */
public class CierreCajaJFrame extends javax.swing.JDialog {

	/**
	 * Creates new form CierreCajaJFrame
	 */
	public CierreCajaJFrame(final Frame parent) {
		super(parent, true);
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saldoInicial = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        estimado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        neto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saldoFinal = new javax.swing.JTextField();
        cierreAnormalPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        diferencia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        observaciones = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        usuarioAutorizo = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        generaFrase = new javax.swing.JButton();
        frase = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        token = new javax.swing.JTextField();
        resultadoToken = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setTitle("CIERRE DE CAJA");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 200));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CajaLlena_1.png"))); // NOI18N
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1);

        jPanel13.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel12.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SALDO INICIAL :");
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel2.add(jLabel2);

        saldoInicial.setEditable(false);
        saldoInicial.setColumns(6);
        saldoInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(saldoInicial);

        jPanel12.add(jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("IMPORTE ESTIMADO: BRUTO :");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel4.add(jLabel4);

        estimado.setEditable(false);
        estimado.setColumns(6);
        estimado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        estimado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(estimado);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NETO:");
        jPanel4.add(jLabel1);

        neto.setEditable(false);
        neto.setColumns(6);
        neto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        neto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(neto);

        jPanel12.add(jPanel4);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("SALDO FINAL :");
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel3.add(jLabel3);

        saldoFinal.setColumns(6);
        saldoFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldoFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(saldoFinal);

        jPanel12.add(jPanel3);

        jPanel13.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        cierreAnormalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CIERRE CON ANORMALIDADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        cierreAnormalPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("IMPORTE DIFERENCIA :");
        jLabel5.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel5.add(jLabel5);

        diferencia.setEditable(false);
        diferencia.setColumns(6);
        diferencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        diferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(diferencia);

        cierreAnormalPanel.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("JUSTIFICACIÓN DE LA DIFERENCIA :");
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel6.add(jLabel6);

        observaciones.setColumns(20);
        observaciones.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jPanel6.add(observaciones);

        cierreAnormalPanel.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("AUTORIZÓ DIFERENCIA :");
        jLabel7.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel7.add(jLabel7);

        usuarioAutorizo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(usuarioAutorizo);

        cierreAnormalPanel.add(jPanel7);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        generaFrase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        generaFrase.setText("OBTENER FRASE :");
        jPanel11.add(generaFrase);

        jPanel10.add(jPanel11);

        frase.setEditable(false);
        frase.setColumns(6);
        frase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        frase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel10.add(frase);

        cierreAnormalPanel.add(jPanel10);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("TOKEN  :");
        jLabel8.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel8.add(jLabel8);

        token.setColumns(6);
        token.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel8.add(token);

        resultadoToken.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultadoToken.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel8.add(resultadoToken);

        cierreAnormalPanel.add(jPanel8);

        jPanel13.add(cierreAnormalPanel, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        jPanel9.add(aceptar);

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelar.setText("CANCELAR");
        jPanel9.add(cancelar);

        jPanel13.add(jPanel9, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel13);

        setSize(new java.awt.Dimension(1183, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel cierreAnormalPanel;
    private javax.swing.JTextField diferencia;
    private javax.swing.JTextField estimado;
    private javax.swing.JTextField frase;
    private javax.swing.JButton generaFrase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField neto;
    private javax.swing.JTextField observaciones;
    private javax.swing.JLabel resultadoToken;
    private javax.swing.JTextField saldoFinal;
    private javax.swing.JTextField saldoInicial;
    private javax.swing.JTextField token;
    private javax.swing.JComboBox usuarioAutorizo;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the aceptar
	 */
	public javax.swing.JButton getAceptar() {
		return aceptar;
	}

	/**
	 * @return the cancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the diferencia
	 */
	public javax.swing.JTextField getDiferencia() {
		return diferencia;
	}

	/**
	 * @return the estimado
	 */
	public javax.swing.JTextField getEstimado() {
		return estimado;
	}

	/**
	 * @return the frase
	 */
	public javax.swing.JTextField getFrase() {
		return frase;
	}

	/**
	 * @return the generaFrase
	 */
	public javax.swing.JButton getGeneraFrase() {
		return generaFrase;
	}

	/**
	 * @return the observaciones
	 */
	public javax.swing.JTextField getObservaciones() {
		return observaciones;
	}

	/**
	 * @return the resultadoToken
	 */
	public javax.swing.JLabel getResultadoToken() {
		return resultadoToken;
	}

	/**
	 * @return the saldoFinal
	 */
	public javax.swing.JTextField getSaldoFinal() {
		return saldoFinal;
	}

	/**
	 * @return the saldoInicial
	 */
	public javax.swing.JTextField getSaldoInicial() {
		return saldoInicial;
	}

	/**
	 * @return the token
	 */
	public javax.swing.JTextField getToken() {
		return token;
	}

	/**
	 * @return the usuarioAutorizo
	 */
	public javax.swing.JComboBox getUsuarioAutorizo() {
		return usuarioAutorizo;
	}

	public JPanel getCierreAnormalPanel() {
		return cierreAnormalPanel;
	}

	public JTextField getNeto() {
		return neto;
	}
	
}
