/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author alfredo
 */
public class CierreCajaJFrame extends javax.swing.JDialog {

	/**
	 * Creates new form CierreCajaJFrame
	 */
	public CierreCajaJFrame(final Frame parent) {
		super(parent, true);
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        panelsParametros = new javax.swing.JTabbedPane();
        cierreNormalPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saldoInicial = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        neto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        estimado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saldoFinal = new javax.swing.JTextField();
        validar = new javax.swing.JButton();
        cierreAnormalPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        resultadoToken = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        diferencia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        justificacion = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        usuarioAutorizo = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();

        setTitle("CIERRE DE CAJA");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 200));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CajaLlena_1.png"))); // NOI18N
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1);

        jPanel13.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        jPanel9.add(aceptar);

        limpiar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        limpiar.setText("LIMPIAR");
        jPanel9.add(limpiar);

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelar.setText("CANCELAR");
        jPanel9.add(cancelar);

        jPanel13.add(jPanel9, java.awt.BorderLayout.SOUTH);

        panelsParametros.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        cierreNormalPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SALDO INICIAL :");
        jLabel2.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel2.add(jLabel2);

        saldoInicial.setEditable(false);
        saldoInicial.setColumns(6);
        saldoInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldoInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(saldoInicial);

        cierreNormalPanel.add(jPanel2);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("SALDO AL FINAL :");
        jLabel10.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel12.add(jLabel10);

        neto.setEditable(false);
        neto.setColumns(6);
        neto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        neto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel12.add(neto);

        cierreNormalPanel.add(jPanel12);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("TOTAL VENTAS - DEVOLUCIONES:");
        jLabel4.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel4.add(jLabel4);

        estimado.setEditable(false);
        estimado.setColumns(18);
        estimado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        estimado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(estimado);

        cierreNormalPanel.add(jPanel4);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("SALDO TOTAL ENTREGADO:");
        jLabel3.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel3.add(jLabel3);

        saldoFinal.setColumns(6);
        saldoFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldoFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(saldoFinal);

        validar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        validar.setText("VALIDAR");
        jPanel3.add(validar);

        cierreNormalPanel.add(jPanel3);

        panelsParametros.addTab("CIERRE NORMAL", cierreNormalPanel);

        cierreAnormalPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        resultadoToken.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultadoToken.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel8.add(resultadoToken);

        cierreAnormalPanel.add(jPanel8);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("IMPORTE DIFERENCIA :");
        jLabel5.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel5.add(jLabel5);

        diferencia.setEditable(false);
        diferencia.setColumns(6);
        diferencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        diferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(diferencia);

        cierreAnormalPanel.add(jPanel5);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("JUSTIFICACIÓN DE LA DIFERENCIA :");
        jLabel6.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel6.add(jLabel6);

        justificacion.setColumns(22);
        justificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        justificacion.setRows(3);
        jScrollPane1.setViewportView(justificacion);

        jPanel6.add(jScrollPane1);

        cierreAnormalPanel.add(jPanel6);

        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0);
        flowLayout3.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("AUTORIZÓ DIFERENCIA :");
        jLabel7.setPreferredSize(new java.awt.Dimension(430, 32));
        jPanel7.add(jLabel7);

        usuarioAutorizo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(usuarioAutorizo);

        cierreAnormalPanel.add(jPanel7);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));
        cierreAnormalPanel.add(jPanel10);

        panelsParametros.addTab("INCONSISTENCIAS", cierreAnormalPanel);

        jPanel13.add(panelsParametros, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel13);

        setSize(new java.awt.Dimension(1119, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel cierreAnormalPanel;
    private javax.swing.JPanel cierreNormalPanel;
    private javax.swing.JTextField diferencia;
    private javax.swing.JTextField estimado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea justificacion;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField neto;
    private javax.swing.JTabbedPane panelsParametros;
    private javax.swing.JLabel resultadoToken;
    private javax.swing.JTextField saldoFinal;
    private javax.swing.JTextField saldoInicial;
    private javax.swing.JComboBox usuarioAutorizo;
    private javax.swing.JButton validar;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the aceptar
	 */
	public javax.swing.JButton getAceptar() {
		return aceptar;
	}

	/**
	 * @return the cancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the diferencia
	 */
	public javax.swing.JTextField getDiferencia() {
		return diferencia;
	}

	/**
	 * @return the estimado
	 */
	public javax.swing.JTextField getEstimado() {
		return estimado;
	}


	/**
	 * @return the resultadoToken
	 */
	public javax.swing.JLabel getResultadoToken() {
		return resultadoToken;
	}

	/**
	 * @return the saldoFinal
	 */
	public javax.swing.JTextField getSaldoFinal() {
		return saldoFinal;
	}

	/**
	 * @return the saldoInicial
	 */
	public javax.swing.JTextField getSaldoInicial() {
		return saldoInicial;
	}

	/**
	 * @return the usuarioAutorizo
	 */
	public javax.swing.JComboBox getUsuarioAutorizo() {
		return usuarioAutorizo;
	}

	public JPanel getCierreAnormalPanel() {
		return cierreAnormalPanel;
	}

	public JPanel getCierreNormalPanel() {
		return cierreNormalPanel;
	}

	public JTabbedPane getPanelsParametros() {
		return panelsParametros;
	}
	
	public JTextField getNeto() {
		return neto;
	}

	/**
	 * @return the justificacion
	 */
	public javax.swing.JTextArea getJustificacion() {
		return justificacion;
	}

	/**
	 * @return the limpiar
	 */
	public javax.swing.JButton getLimpiar() {
		return limpiar;
	}

	/**
	 * @return the validar
	 */
	public javax.swing.JButton getValidar() {
		return validar;
	}
	
}
