/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pmarlen.caja.view;

import com.pmarlen.caja.model.Caja;
import com.pmarlen.caja.model.Sucursal;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author alfredo
 */
public class FirstRunParamsConfigDialog extends javax.swing.JFrame {

	/**
	 * Creates new form FirstRunParamsConfigDialog
	 */
	public FirstRunParamsConfigDialog() {
		super("PM Caja >> Inicialización");
		initComponents();
		Object[] sucs=new Sucursal[]{
			new Sucursal(2, "SUC#1 SAN MARTÍN"),
			new Sucursal(3, "SUC#2 TECAMAC"),
			new Sucursal(4, "SUC#3 OJO DE AGUA"),
			new Sucursal(5, "SUC#4 LOS REYES")
		};
		Object[] cajas=new Caja[]{
			new Caja(1, "CAJA #1"),
			new Caja(2, "CAJA #2"),
			new Caja(3, "CAJA #3"),
			new Caja(4, "CAJA #4"),
			new Caja(5, "CAJA #5"),
			new Caja(6, "CAJA #6"),
			new Caja(7, "CAJA #7")
		};
		
		sucursal.setModel(new DefaultComboBoxModel(sucs));
		caja.setModel(new DefaultComboBoxModel(cajas));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        server = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dropBoxDir = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sucursal = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        caja = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        centerPanel.setLayout(new java.awt.GridLayout(5, 1));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("SERVIDOR :");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jLabel1);

        server.setColumns(20);
        jPanel2.add(server);

        centerPanel.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("PUERTO :");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel3.add(jLabel2);

        port.setColumns(3);
        jPanel3.add(port);

        centerPanel.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DIRECTORIO DROPBOX :");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel4.add(jLabel3);

        dropBoxDir.setColumns(20);
        jPanel4.add(dropBoxDir);

        centerPanel.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SUCURSAL :");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(jLabel4);
        jPanel5.add(sucursal);

        centerPanel.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CAJA # :");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel6.add(jLabel5);
        jPanel6.add(caja);

        centerPanel.add(jPanel6);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        guardar.setText("GUARDAR");
        jPanel1.add(guardar);

        cancelar.setText("CANCELAR");
        jPanel1.add(cancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel7.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel6.setIcon(getImageIcon());
        jPanel7.add(jLabel6);

        getContentPane().add(jPanel7, java.awt.BorderLayout.WEST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	ImageIcon getImageIcon(){
		ImageIcon icon = null;
		try{
			icon = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/install.png")));
		} catch(Exception e){
		
		}
		return icon;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox caja;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField dropBoxDir;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField port;
    private javax.swing.JTextField server;
    private javax.swing.JComboBox sucursal;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the cancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the dropBoxDir
	 */
	public javax.swing.JTextField getDropBoxDir() {
		return dropBoxDir;
	}

	/**
	 * @return the guardar
	 */
	public javax.swing.JButton getGuardar() {
		return guardar;
	}

	/**
	 * @return the port
	 */
	public javax.swing.JTextField getPort() {
		return port;
	}

	/**
	 * @return the server
	 */
	public javax.swing.JTextField getServer() {
		return server;
	}

	public JComboBox getSucursal() {
		return sucursal;
	}

	public JComboBox getCaja() {
		return caja;
	}
	
}
