/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import com.pmarlen.backend.model.Usuario;
import com.pmarlen.caja.control.ApplicationLogic;
import com.pmarlen.caja.dao.MemoryDAO;
import com.pmarlen.rest.dto.U;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.annotation.PostConstruct;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextField;
import org.apache.log4j.Logger;

/**
 *
 * @author alfredo
 */
public class FramePrincipal extends javax.swing.JFrame {
	private static Logger logger = Logger.getLogger(FramePrincipal.class.getName());
	private static int prevStatus = -1;
	/**
	 * Creates new form FramePrincipal
	 */
	public FramePrincipal() {
		logger.debug("FramePrincipal():");
		initComponents();
		logger.debug("FramePrincipal(): after initComponents");
		prepareComponents();
	}
	
	private void prepareComponents(){
		logger.debug("prepareComponents():pml30ImageIcon="+pml30ImageIcon);
		if(pml30ImageIcon != null){
			logoLabel.setText(null);
		}
		preareAbrirSesion();
	}
	
	public void preareAbrirSesion(){

		this.abrirSesion.setEnabled(true);
		this.archivoMenu.setEnabled(true);
		this.emailSoporteMenu.setEnabled(true);
		this.helpMenu.setEnabled(true);
		this.manualMenu.setEnabled(true);
		this.salirMenu.setEnabled(true);
		this.sesionMenu.setEnabled(true);		
		this.acercaDeMenu.setEnabled(true);
		this.portalMenu.setEnabled(true);
		
		this.cerrarSesion.setEnabled(true);		
		this.cerrarSesion.setVisible(false);
		
		this.cancelarDevolMenu.setEnabled(false);		
		this.coneccionMenu.setEnabled(false);
		this.configMenu.setEnabled(false);
		this.devolMenu.setEnabled(false);
		this.devolsMenu.setEnabled(false);
		this.impresionBluetothMenu.setEnabled(false);
		this.impresionMenu.setEnabled(false);
		this.impresionParamMenu.setEnabled(false);
		this.impresionPruebaMenu.setEnabled(false);
		this.impresionSistemaMenu.setEnabled(false);
		this.nuevaDevolMenu.setEnabled(false);
		this.terminarDevolMenu.setEnabled(false);
		this.ventaCancelarMenu.setEnabled(false);
		this.ventaMenu.setEnabled(false);
		this.ventaModoMenu.setEnabled(false);
		this.ventaTerminarMenu.setEnabled(false);
		this.ventaeliminarProdMenu.setEnabled(false);
		this.ventasMenu.setEnabled(false);	
	}

	public void enableMinimalComponents(){
		logger.debug("enableMinimalComponents()");

		this.abrirSesion.setEnabled(false);
		this.abrirSesion.setVisible(false);
		
		this.archivoMenu.setEnabled(true);
		this.emailSoporteMenu.setEnabled(true);
		this.helpMenu.setEnabled(true);
		this.manualMenu.setEnabled(true);
		this.salirMenu.setEnabled(true);
		this.sesionMenu.setEnabled(true);		
		this.acercaDeMenu.setEnabled(true);
		this.portalMenu.setEnabled(true);
		
		this.cerrarSesion.setEnabled(true);		
		this.cerrarSesion.setVisible(true);
		
		this.cancelarDevolMenu.setEnabled(true);		
		this.coneccionMenu.setEnabled(true);
		this.devolMenu.setEnabled(true);
		this.devolsMenu.setEnabled(true);
		this.impresionBluetothMenu.setEnabled(true);
		this.impresionMenu.setEnabled(true);
		this.impresionParamMenu.setEnabled(true);
		this.impresionPruebaMenu.setEnabled(true);
		this.impresionSistemaMenu.setEnabled(true);
		this.nuevaDevolMenu.setEnabled(true);
		this.terminarDevolMenu.setEnabled(true);
		this.ventaCancelarMenu.setEnabled(true);
		this.ventaMenu.setEnabled(true);
		this.ventaModoMenu.setEnabled(true);
		this.ventaTerminarMenu.setEnabled(true);
		this.ventaeliminarProdMenu.setEnabled(true);
		this.ventasMenu.setEnabled(true);
	}

	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoImpresion = new javax.swing.ButtonGroup();
        panels = new javax.swing.JPanel();
        panelSesion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        abrirSesion = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        panelVenta = new PanelVenta();
        panelVentas = new PanelVentas();
        statusPanel = new javax.swing.JPanel();
        statusWest = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        statusCenter = new javax.swing.JTextField();
        statusConeccion = new javax.swing.JTextField();
        notificaciones = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        sesionMenu = new javax.swing.JMenuItem();
        ventasMenu = new javax.swing.JMenuItem();
        devolsMenu = new javax.swing.JMenuItem();
        notificacionesMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirMenu = new javax.swing.JMenuItem();
        ventaMenu = new javax.swing.JMenu();
        ventaTerminarMenu = new javax.swing.JMenuItem();
        ventaActualMenu = new javax.swing.JMenuItem();
        ventaLineaMenu = new javax.swing.JMenuItem();
        ventaOportunidadMenu = new javax.swing.JMenuItem();
        ventaRegaliasMenu = new javax.swing.JMenuItem();
        ventaModoMenu = new javax.swing.JMenuItem();
        ventaCancelarMenu = new javax.swing.JMenuItem();
        ventaeliminarProdMenu = new javax.swing.JMenuItem();
        devolMenu = new javax.swing.JMenu();
        nuevaDevolMenu = new javax.swing.JMenuItem();
        terminarDevolMenu = new javax.swing.JMenuItem();
        cancelarDevolMenu = new javax.swing.JMenuItem();
        configMenu = new javax.swing.JMenu();
        coneccionMenu = new javax.swing.JMenuItem();
        impresionMenu = new javax.swing.JMenu();
        impresionParamMenu = new javax.swing.JMenuItem();
        impresionSistemaMenu = new javax.swing.JRadioButtonMenuItem();
        impresionBluetothMenu = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        impresionPruebaMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        manualMenu = new javax.swing.JMenuItem();
        portalMenu = new javax.swing.JMenuItem();
        emailSoporteMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        acercaDeMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja");
        setIconImage(getPml30WindowImageIcon());

        panels.setLayout(new java.awt.CardLayout());

        panelSesion.setBorder(javax.swing.BorderFactory.createTitledBorder("Sesión"));
        panelSesion.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(getPml30ImageIcon());
        logoLabel.setText("PML30-CAJA");
        jPanel1.add(logoLabel, java.awt.BorderLayout.CENTER);

        panelSesion.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 50));

        abrirSesion.setBackground(java.awt.Color.green);
        abrirSesion.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        abrirSesion.setText("ABRIR CAJA");
        jPanel2.add(abrirSesion);

        cerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        cerrarSesion.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        cerrarSesion.setText("CERRAR CAJA");
        jPanel2.add(cerrarSesion);

        panelSesion.add(jPanel2, java.awt.BorderLayout.SOUTH);

        panels.add(panelSesion, "panelSesion");

        panelVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta Actual"));
        panels.add(panelVenta, "panelVenta");

        panelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));
        panels.add(panelVentas, "panelVentas");

        getContentPane().add(panels, java.awt.BorderLayout.CENTER);

        statusPanel.setPreferredSize(new java.awt.Dimension(42, 35));
        statusPanel.setLayout(new java.awt.BorderLayout());

        statusWest.setEditable(false);
        statusWest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusPanel.add(statusWest, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(380, 30));
        jPanel3.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        statusCenter.setEditable(false);
        statusCenter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(statusCenter);

        statusConeccion.setEditable(false);
        statusConeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(statusConeccion);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        notificaciones.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        notificaciones.setText("00");
        notificaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notificaciones.setIconTextGap(0);
        notificaciones.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel3.add(notificaciones, java.awt.BorderLayout.EAST);

        statusPanel.add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(statusPanel, java.awt.BorderLayout.SOUTH);

        archivoMenu.setText("Archivo");

        sesionMenu.setText("Sesión");
        archivoMenu.add(sesionMenu);

        ventasMenu.setText("H. Ventas");
        archivoMenu.add(ventasMenu);

        devolsMenu.setText("H. Devol");
        archivoMenu.add(devolsMenu);

        notificacionesMenu.setText("Notificaciones");
        archivoMenu.add(notificacionesMenu);
        archivoMenu.add(jSeparator1);

        salirMenu.setText("Salir");
        archivoMenu.add(salirMenu);

        jMenuBar1.add(archivoMenu);

        ventaMenu.setText("Venta");

        ventaTerminarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        ventaTerminarMenu.setText("Terminar");
        ventaMenu.add(ventaTerminarMenu);

        ventaActualMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        ventaActualMenu.setText("Actual");
        ventaMenu.add(ventaActualMenu);

        ventaLineaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        ventaLineaMenu.setText("1ra Linea");
        ventaMenu.add(ventaLineaMenu);

        ventaOportunidadMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        ventaOportunidadMenu.setText("Oportunidad");
        ventaMenu.add(ventaOportunidadMenu);

        ventaRegaliasMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        ventaRegaliasMenu.setText("Regalias");
        ventaMenu.add(ventaRegaliasMenu);

        ventaModoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        ventaModoMenu.setText("Agregar/Checar");
        ventaMenu.add(ventaModoMenu);

        ventaCancelarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        ventaCancelarMenu.setText("Cancelar");
        ventaMenu.add(ventaCancelarMenu);

        ventaeliminarProdMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        ventaeliminarProdMenu.setText("Eliminar Producto");
        ventaMenu.add(ventaeliminarProdMenu);

        jMenuBar1.add(ventaMenu);

        devolMenu.setText("Devolución");

        nuevaDevolMenu.setText("Nueva");
        devolMenu.add(nuevaDevolMenu);

        terminarDevolMenu.setText("Terminar");
        devolMenu.add(terminarDevolMenu);

        cancelarDevolMenu.setText("Cancelar");
        devolMenu.add(cancelarDevolMenu);

        jMenuBar1.add(devolMenu);

        configMenu.setText("Configuración");

        coneccionMenu.setText("Sesión de Caja");
        configMenu.add(coneccionMenu);

        impresionMenu.setText("Impresión");

        impresionParamMenu.setText("Parametros");
        impresionMenu.add(impresionParamMenu);

        tipoImpresion.add(impresionSistemaMenu);
        impresionSistemaMenu.setSelected(true);
        impresionSistemaMenu.setText("De Sistema");
        impresionMenu.add(impresionSistemaMenu);

        tipoImpresion.add(impresionBluetothMenu);
        impresionBluetothMenu.setText("Bluetooth");
        impresionMenu.add(impresionBluetothMenu);
        impresionMenu.add(jSeparator2);

        impresionPruebaMenu.setText("Enviar prueba");
        impresionMenu.add(impresionPruebaMenu);

        configMenu.add(impresionMenu);

        jMenuBar1.add(configMenu);

        helpMenu.setText("Ayuda");

        manualMenu.setText("Manual de Usuario");
        helpMenu.add(manualMenu);

        portalMenu.setText("Portal L30");
        helpMenu.add(portalMenu);

        emailSoporteMenu.setText("Email Soporte");
        helpMenu.add(emailSoporteMenu);
        helpMenu.add(jSeparator3);

        acercaDeMenu.setText("Acerca de");
        helpMenu.add(acercaDeMenu);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1018, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirSesion;
    private javax.swing.JMenuItem acercaDeMenu;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenuItem cancelarDevolMenu;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JMenuItem coneccionMenu;
    private javax.swing.JMenu configMenu;
    private javax.swing.JMenu devolMenu;
    private javax.swing.JMenuItem devolsMenu;
    private javax.swing.JMenuItem emailSoporteMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JRadioButtonMenuItem impresionBluetothMenu;
    private javax.swing.JMenu impresionMenu;
    private javax.swing.JMenuItem impresionParamMenu;
    private javax.swing.JMenuItem impresionPruebaMenu;
    private javax.swing.JRadioButtonMenuItem impresionSistemaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JMenuItem manualMenu;
    private javax.swing.JButton notificaciones;
    private javax.swing.JMenuItem notificacionesMenu;
    private javax.swing.JMenuItem nuevaDevolMenu;
    private javax.swing.JPanel panelSesion;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JPanel panels;
    private javax.swing.JMenuItem portalMenu;
    private javax.swing.JMenuItem salirMenu;
    private javax.swing.JMenuItem sesionMenu;
    private javax.swing.JTextField statusCenter;
    private javax.swing.JTextField statusConeccion;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField statusWest;
    private javax.swing.JMenuItem terminarDevolMenu;
    private javax.swing.ButtonGroup tipoImpresion;
    private javax.swing.JMenuItem ventaActualMenu;
    private javax.swing.JMenuItem ventaCancelarMenu;
    private javax.swing.JMenuItem ventaLineaMenu;
    private javax.swing.JMenu ventaMenu;
    private javax.swing.JMenuItem ventaModoMenu;
    private javax.swing.JMenuItem ventaOportunidadMenu;
    private javax.swing.JMenuItem ventaRegaliasMenu;
    private javax.swing.JMenuItem ventaTerminarMenu;
    private javax.swing.JMenuItem ventaeliminarProdMenu;
    private javax.swing.JMenuItem ventasMenu;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the archivoMenu
	 */
	public javax.swing.JMenu getArchivoMenu() {
		return archivoMenu;
	}

	/**
	 * @return the panelVenta
	 */
	public PanelVenta getPanelVenta() {
		return (PanelVenta)panelVenta;
	}

	/**
	 * @return the panels
	 */
	public javax.swing.JPanel getPanels() {
		return panels;
	}

	/**
	 * @return the productosMenu
	 */
	public javax.swing.JMenuItem getProductosMenu() {
		return devolsMenu;
	}

	/**
	 * @return the salirMenu
	 */
	public javax.swing.JMenuItem getSalirMenu() {
		return salirMenu;
	}

	/**
	 * @return the ventaCancelarMenu
	 */
	public javax.swing.JMenuItem getVentaCancelarMenu() {
		return ventaCancelarMenu;
	}

	/**
	 * @return the ventaMenu
	 */
	public javax.swing.JMenu getVentaMenu() {
		return ventaMenu;
	}

	/**
	 * @return the ventaActualMenu
	 */
	public JMenuItem getVentaActualMenu() {
		return ventaActualMenu;
	}

	/**
	 * @return the ventaTerminarMenu
	 */
	public javax.swing.JMenuItem getVentaTerminarMenu() {
		return ventaTerminarMenu;
	}

	/**
	 * @return the ventaeliminarProdMenu
	 */
	public javax.swing.JMenuItem getVentaeliminarProdMenu() {
		return ventaeliminarProdMenu;
	}

	/**
	 * @return the ventasMenu
	 */
	public javax.swing.JMenuItem getVentasMenu() {
		return ventasMenu;
	}

	/**
	 * @return the panelVentas
	 */
	public javax.swing.JPanel getPanelVentas() {
		return panelVentas;
	}
	
	/**
	 * @return the negocioConfigMenu
	 */
	public javax.swing.JMenuItem getNegocioConfigMenu() {
		return coneccionMenu;
	}

	/**
	 * @return the configMenu
	 */
	public javax.swing.JMenu getConfigMenu() {
		return configMenu;
	}

	public JTextField getStatusConeccion() {
		return statusConeccion;
	}

	public JTextField getStatusWest() {
		return statusWest;
	}

	public JTextField getStatusCenter() {
		return statusCenter;
	}

	public JMenuItem getVentaModoMenu() {
		return ventaModoMenu;
	}
	
	public void updateStatus(){
		int s= MemoryDAO.getSyncPollState();
		
		if(prevStatus == -1){
			prevStatus = s;
		}
		
		if(s == MemoryDAO.SYNC_STATE_BEFORE_RUNNING) {
			if(prevStatus >= MemoryDAO.SYNC_STATE_IO_ERROR){
				statusConeccion.setBackground(Color.RED);
			} else {
				statusConeccion.setBackground(Color.YELLOW);
			}
			statusConeccion.setBackground(Color.YELLOW);
			statusConeccion.setText("..PREPARADO");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_CONNECTING) {
			if(prevStatus >= MemoryDAO.SYNC_STATE_IO_ERROR){
				statusConeccion.setBackground(Color.RED);
			} else {
				statusConeccion.setBackground(Color.YELLOW);
			}
			statusConeccion.setText("..CONECTANDO DT");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_CONNECTINGLIVE) {
			if(prevStatus >= MemoryDAO.SYNC_STATE_IO_ERROR){
				statusConeccion.setBackground(Color.RED);
			} else {
				statusConeccion.setBackground(Color.YELLOW);
			}
			statusConeccion.setText("..CONECTANDO SL");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_DOWNLOADED ) {
			statusConeccion.setBackground(Color.GREEN);
			statusConeccion.setText("DATOS DESCARGADOS");
		} else if(s == MemoryDAO.SYNC_STATE_READ ) {
			statusConeccion.setBackground(Color.GREEN);
			statusConeccion.setText("EN LINEA / DATOS");
		} else if(s == MemoryDAO.SYNC_STATE_IMLIVE ) {
			statusConeccion.setBackground(Color.GREEN);
			statusConeccion.setText("EN LINEA / REGISTRO");
		} else if(s == MemoryDAO.SYNC_STATE_SERVER_4XX ) {
			statusConeccion.setBackground(Color.RED);
			statusConeccion.setText("ERROR SERV 4XX");
		} else if(s == MemoryDAO.SYNC_STATE_SERVER_5XX ) {
			statusConeccion.setBackground(Color.RED);
			statusConeccion.setText("ERROR SERV 5XX");
		} else if(s == MemoryDAO.SYNC_STATE_CONNECTION ) {
			statusConeccion.setBackground(Color.RED);
			statusConeccion.setText("NO RED/SERVIDOR");
		} else if(s == MemoryDAO.SYNC_STATE_IO_ERROR ) {
			statusConeccion.setBackground(Color.RED);
			statusConeccion.setText("ERROR E/S");
		} else if(s == MemoryDAO.SYNC_STATE_ERROR) {
			statusConeccion.setBackground(Color.RED);
			statusConeccion.setText("ERROR GRAVE");
		} else {
			statusConeccion.setBackground(Color.GRAY);
			statusConeccion.setText("ERROR ???");
		}
		
		statusConeccion.setToolTipText("STATUS:"+s);				
	}
	
	public void updateStatusWest(String info){
		//statusConeccion.set_Foreground(Color.DARK_GRAY);
		statusWest.setText(info);		
	}
	
	public void setFont(Font font){
		panelSesion.setFont(font);
		panelVenta.setFont(font);
		panelVentas.setFont(font);
		statusPanel.setFont(font);
	}
	
	private ImageIcon pml30ImageIcon = null;
	
	private Image pml30WindowImageIcon = null;
	
	private Icon getPml30ImageIcon() {
		if(pml30ImageIcon ==null){
			try{
				pml30ImageIcon = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/imgs/L30_252x252_Ver1.png")));
			} catch(Exception e){
				e.printStackTrace(System.err);
			}
		}
		return pml30ImageIcon;
	
	}

	public Image getPml30WindowImageIcon() {		
		if(pml30WindowImageIcon == null){
			try{
				pml30WindowImageIcon = ImageIO.read(getClass().getResourceAsStream("/imgs/L30_64x64_Ver1.png"));
			} catch(Exception e){
				e.printStackTrace(System.err);
			}
		}
		return pml30WindowImageIcon;
	}

	/**
	 * @return the abrirSesionBtn
	 */
	public javax.swing.JButton getAbrirSesion() {
		return abrirSesion;
	}

	/**
	 * @return the acercaDeMenu
	 */
	public javax.swing.JMenuItem getAcercaDeMenu() {
		return acercaDeMenu;
	}

	/**
	 * @return the cancelarDevolMenu
	 */
	public javax.swing.JMenuItem getCancelarDevolMenu() {
		return cancelarDevolMenu;
	}
	
	/**
	 * @return the cerrarSesion
	 */
	public javax.swing.JButton getCerrarSesion() {
		return cerrarSesion;
	}

	/**
	 * @return the coneccionMenu
	 */
	public javax.swing.JMenuItem getConeccionMenu() {
		return coneccionMenu;
	}

	/**
	 * @return the devolMenu
	 */
	public javax.swing.JMenu getDevolMenu() {
		return devolMenu;
	}

	/**
	 * @return the devolsMenu
	 */
	public javax.swing.JMenuItem getDevolsMenu() {
		return devolsMenu;
	}

	/**
	 * @return the emailSoporteMenu
	 */
	public javax.swing.JMenuItem getEmailSoporteMenu() {
		return emailSoporteMenu;
	}

	/**
	 * @return the helpMenu
	 */
	public javax.swing.JMenu getHelpMenu() {
		return helpMenu;
	}

	/**
	 * @return the impresionBluetothMenu
	 */
	public javax.swing.JRadioButtonMenuItem getImpresionBluetothMenu() {
		return impresionBluetothMenu;
	}

	/**
	 * @return the impresionMenu
	 */
	public javax.swing.JMenu getImpresionMenu() {
		return impresionMenu;
	}

	/**
	 * @return the impresionParamMenu
	 */
	public javax.swing.JMenuItem getImpresionParamMenu() {
		return impresionParamMenu;
	}

	/**
	 * @return the impresionPruebaMenu
	 */
	public javax.swing.JMenuItem getImpresionPruebaMenu() {
		return impresionPruebaMenu;
	}

	/**
	 * @return the impresionSistemaMenu
	 */
	public javax.swing.JRadioButtonMenuItem getImpresionSistemaMenu() {
		return impresionSistemaMenu;
	}

	/**
	 * @return the logoLabel
	 */
	public javax.swing.JLabel getLogoLabel() {
		return logoLabel;
	}

	/**
	 * @return the manualMenu
	 */
	public javax.swing.JMenuItem getManualMenu() {
		return manualMenu;
	}

	/**
	 * @return the nuevaDevolMenu
	 */
	public javax.swing.JMenuItem getNuevaDevolMenu() {
		return nuevaDevolMenu;
	}

	/**
	 * @return the panelSesion
	 */
	public javax.swing.JPanel getPanelSesion() {
		return panelSesion;
	}

	/**
	 * @return the portalMenu
	 */
	public javax.swing.JMenuItem getPortalMenu() {
		return portalMenu;
	}

	/**
	 * @return the sesionMenu
	 */
	public javax.swing.JMenuItem getSesionMenu() {
		return sesionMenu;
	}

	/**
	 * @return the statusPanel
	 */
	public javax.swing.JPanel getStatusPanel() {
		return statusPanel;
	}

	/**
	 * @return the terminarDevolMenu
	 */
	public javax.swing.JMenuItem getTerminarDevolMenu() {
		return terminarDevolMenu;
	}

	/**
	 * @return the tipoImpresion
	 */
	public javax.swing.ButtonGroup getTipoImpresion() {
		return tipoImpresion;
	}

	public JMenuItem getVentaLineaMenu() {
		return ventaLineaMenu;
	}

	public JMenuItem getVentaOportunidadMenu() {
		return ventaOportunidadMenu;
	}

	public JMenuItem getVentaRegaliasMenu() {
		return ventaRegaliasMenu;
	}

	public JButton getNotificaciones() {
		return notificaciones;
	}

	public JMenuItem getNotificacionesMenu() {
		return notificacionesMenu;
	}
	
}
