/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import com.pmarlen.backend.model.Usuario;
import com.pmarlen.caja.control.ApplicationLogic;
import com.pmarlen.caja.dao.MemoryDAO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author alfredo
 */
public class FramePrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form FramePrincipal
	 */
	public FramePrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoImpresion = new javax.swing.ButtonGroup();
        panels = new javax.swing.JPanel();
        panelSesion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelVenta = new PanelVenta();
        panelVentas = new PanelVentas();
        statusPanel = new javax.swing.JPanel();
        statusWest = new javax.swing.JTextField();
        statusCenter = new javax.swing.JTextField();
        statusConeccion = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        ventasMenu = new javax.swing.JMenuItem();
        productosMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirMenu = new javax.swing.JMenuItem();
        ventaMenu = new javax.swing.JMenu();
        ventaActualMenu = new javax.swing.JMenuItem();
        ventaTerminarMenu = new javax.swing.JMenuItem();
        ventaModoMenu = new javax.swing.JMenuItem();
        ventaCancelarMenu = new javax.swing.JMenuItem();
        ventaeliminarProdMenu = new javax.swing.JMenuItem();
        devolMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        configMenu = new javax.swing.JMenu();
        coneccionMenu = new javax.swing.JMenuItem();
        impresionMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja");

        panels.setLayout(new java.awt.CardLayout());

        panelSesion.setBorder(javax.swing.BorderFactory.createTitledBorder("Sesión"));
        panelSesion.setLayout(new java.awt.GridLayout(3, 1, 30, 1));
        panelSesion.add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 100));

        jButton4.setBackground(java.awt.Color.green);
        jButton4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton4.setText("ABRIR");
        jPanel2.add(jButton4);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jButton1.setText("CERRAR");
        jPanel2.add(jButton1);

        panelSesion.add(jPanel2);
        panelSesion.add(jPanel3);

        panels.add(panelSesion, "card4");

        panelVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta Actual"));
        panels.add(panelVenta, "panelVenta");

        panelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));
        panels.add(panelVentas, "panelVentas");

        getContentPane().add(panels, java.awt.BorderLayout.CENTER);

        statusPanel.setPreferredSize(new java.awt.Dimension(42, 35));
        statusPanel.setLayout(new java.awt.GridLayout(1, 3));

        statusWest.setEditable(false);
        statusWest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusPanel.add(statusWest);

        statusCenter.setEditable(false);
        statusCenter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusPanel.add(statusCenter);

        statusConeccion.setEditable(false);
        statusConeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusPanel.add(statusConeccion);

        getContentPane().add(statusPanel, java.awt.BorderLayout.SOUTH);

        archivoMenu.setText("Archivo");

        jMenuItem12.setText("Sesión");
        archivoMenu.add(jMenuItem12);

        ventasMenu.setText("H. Ventas");
        archivoMenu.add(ventasMenu);

        productosMenu.setText("H. Devol");
        archivoMenu.add(productosMenu);
        archivoMenu.add(jSeparator1);

        salirMenu.setText("Salir");
        archivoMenu.add(salirMenu);

        jMenuBar1.add(archivoMenu);

        ventaMenu.setText("Venta");

        ventaActualMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        ventaActualMenu.setText("Actual");
        ventaMenu.add(ventaActualMenu);

        ventaTerminarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        ventaTerminarMenu.setText("Terminar");
        ventaMenu.add(ventaTerminarMenu);

        ventaModoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        ventaModoMenu.setText("Agregar/Checar");
        ventaMenu.add(ventaModoMenu);

        ventaCancelarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        ventaCancelarMenu.setText("Cancelar");
        ventaMenu.add(ventaCancelarMenu);

        ventaeliminarProdMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        ventaeliminarProdMenu.setText("Eliminar Producto");
        ventaMenu.add(ventaeliminarProdMenu);

        jMenuBar1.add(ventaMenu);

        devolMenu.setText("Devolución");

        jMenuItem1.setText("Nueva");
        devolMenu.add(jMenuItem1);

        jMenuItem2.setText("Terminar");
        devolMenu.add(jMenuItem2);

        jMenuItem3.setText("Cancelar");
        devolMenu.add(jMenuItem3);

        jMenuBar1.add(devolMenu);

        configMenu.setText("Configuración");

        coneccionMenu.setText("Sesión de Caja");
        configMenu.add(coneccionMenu);

        impresionMenu.setText("Impresión");

        jMenuItem5.setText("Parametros");
        impresionMenu.add(jMenuItem5);

        tipoImpresion.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("De Sistema");
        impresionMenu.add(jRadioButtonMenuItem1);

        tipoImpresion.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Bluetooth");
        impresionMenu.add(jRadioButtonMenuItem2);
        impresionMenu.add(jSeparator2);

        jMenuItem4.setText("Enviar prueba");
        impresionMenu.add(jMenuItem4);

        configMenu.add(impresionMenu);

        jMenuBar1.add(configMenu);

        helpMenu.setText("Ayuda");

        jMenuItem8.setText("Manual de Usuario");
        helpMenu.add(jMenuItem8);

        jMenuItem10.setText("Portal L30");
        helpMenu.add(jMenuItem10);

        jMenuItem11.setText("Email Soporte");
        helpMenu.add(jMenuItem11);
        helpMenu.add(jSeparator3);

        jMenuItem9.setText("Acerca de");
        helpMenu.add(jMenuItem9);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1018, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FramePrincipal().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenuItem coneccionMenu;
    private javax.swing.JMenu configMenu;
    private javax.swing.JMenu devolMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu impresionMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPanel panelSesion;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JPanel panels;
    private javax.swing.JMenuItem productosMenu;
    private javax.swing.JMenuItem salirMenu;
    private javax.swing.JTextField statusCenter;
    private javax.swing.JTextField statusConeccion;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField statusWest;
    private javax.swing.ButtonGroup tipoImpresion;
    private javax.swing.JMenuItem ventaActualMenu;
    private javax.swing.JMenuItem ventaCancelarMenu;
    private javax.swing.JMenu ventaMenu;
    private javax.swing.JMenuItem ventaModoMenu;
    private javax.swing.JMenuItem ventaTerminarMenu;
    private javax.swing.JMenuItem ventaeliminarProdMenu;
    private javax.swing.JMenuItem ventasMenu;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the archivoMenu
	 */
	public javax.swing.JMenu getArchivoMenu() {
		return archivoMenu;
	}

	/**
	 * @return the panelVenta
	 */
	public PanelVenta getPanelVenta() {
		return (PanelVenta)panelVenta;
	}

	/**
	 * @return the panels
	 */
	public javax.swing.JPanel getPanels() {
		return panels;
	}

	/**
	 * @return the productosMenu
	 */
	public javax.swing.JMenuItem getProductosMenu() {
		return productosMenu;
	}

	/**
	 * @return the salirMenu
	 */
	public javax.swing.JMenuItem getSalirMenu() {
		return salirMenu;
	}

	/**
	 * @return the ventaCancelarMenu
	 */
	public javax.swing.JMenuItem getVentaCancelarMenu() {
		return ventaCancelarMenu;
	}

	/**
	 * @return the ventaMenu
	 */
	public javax.swing.JMenu getVentaMenu() {
		return ventaMenu;
	}

	/**
	 * @return the ventaActualMenu
	 */
	public javax.swing.JMenuItem getVentaActualMenu() {
		return ventaActualMenu;
	}

	/**
	 * @return the ventaTerminarMenu
	 */
	public javax.swing.JMenuItem getVentaTerminarMenu() {
		return ventaTerminarMenu;
	}

	/**
	 * @return the ventaeliminarProdMenu
	 */
	public javax.swing.JMenuItem getVentaeliminarProdMenu() {
		return ventaeliminarProdMenu;
	}

	/**
	 * @return the ventasMenu
	 */
	public javax.swing.JMenuItem getVentasMenu() {
		return ventasMenu;
	}

	/**
	 * @return the panelVentas
	 */
	public javax.swing.JPanel getPanelVentas() {
		return panelVentas;
	}
	
	/**
	 * @return the negocioConfigMenu
	 */
	public javax.swing.JMenuItem getNegocioConfigMenu() {
		return coneccionMenu;
	}

	/**
	 * @return the configMenu
	 */
	public javax.swing.JMenu getConfigMenu() {
		return configMenu;
	}

	public JTextField getStatusConeccion() {
		return statusConeccion;
	}

	public JTextField getStatusWest() {
		return statusWest;
	}

	public JTextField getStatusCenter() {
		return statusCenter;
	}

	public JMenuItem getVentaModoMenu() {
		return ventaModoMenu;
	}
	
	public void updateStatus(){
		int s= MemoryDAO.getSyncPollState();
		if(s == MemoryDAO.SYNC_STATE_BEFORE_RUNNING) {
			statusConeccion.setForeground(Color.GRAY);
			statusConeccion.setText("..PREPARADO");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_CONNECTING) {
			statusConeccion.setForeground(Color.YELLOW);
			statusConeccion.setText("..CONECTANDO DATOS");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_CONNECTINGLIVE) {
			statusConeccion.setForeground(Color.YELLOW);
			statusConeccion.setText("..CONECTADO LIVE");
		} else if(s == MemoryDAO.SYNC_STATE_BEFORE_DOWNLOADED ) {
			statusConeccion.setForeground(Color.DARK_GRAY);
			statusConeccion.setText("OK DESCARGADO");
		} else if(s == MemoryDAO.SYNC_STATE_READ ) {
			statusConeccion.setForeground(Color.GREEN);
			statusConeccion.setText("DATOS CARGADOS");
		} else if(s == MemoryDAO.SYNC_STATE_IMLIVE ) {
			statusConeccion.setForeground(Color.BLUE);
			statusConeccion.setText("I'M ALIVE");
		} else if(s == MemoryDAO.SYNC_STATE_ERROR_URL ) {
			statusConeccion.setForeground(Color.CYAN);
			statusConeccion.setText("URL ERROR");
		} else if(s == MemoryDAO.SYNC_STATE_ERROR) {
			statusConeccion.setForeground(Color.RED);
			statusConeccion.setText("ERROR");
		} else {
			statusConeccion.setForeground(Color.DARK_GRAY);
			statusConeccion.setText("???");
		}
		
		statusConeccion.setToolTipText("STATUS:"+s);				
	}
	
	public void updateStatusWest(){
		statusConeccion.setForeground(Color.DARK_GRAY);
		Usuario logged = ApplicationLogic.getInstance().getLogged();
		if( logged != null) {
			statusWest.setText(MemoryDAO.getCajaGlobalInfo()+"/"+logged.getEmail());
		} else {
			statusWest.setText(MemoryDAO.getCajaGlobalInfo());
		}
		
	}
	
	public void setFont(Font font){
		panelVenta.setFont(font);
		panelVentas.setFont(font);
		statusPanel.setFont(font);
		
		//statusWest.setFont(font);
		//statusCenter.setFont(font);
		//statusConeccion.setFont(font);
	}
}
