/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import com.pmarlen.caja.model.VentaTableModel;
import javax.swing.JButton;

/**
 *
 * @author alfredo
 */
public class PanelVentas extends javax.swing.JPanel {

	/**
	 * Creates new form PanelVenta
	 */
	public PanelVentas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ventasJTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        reimprimir = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(ventasJTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        reimprimir.setText("REIMPRIMIR TICKET");
        jPanel3.add(reimprimir);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reimprimir;
    private javax.swing.JTable ventasJTable;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the ventasJTable
	 */
	public javax.swing.JTable getVentasJTable() {
		return ventasJTable;
	}

	public JButton getReimprimir() {
		return reimprimir;
	}
	
}
