/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.caja.view;

import java.awt.Font;
import java.text.DecimalFormat;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import org.apache.log4j.Logger;

/**
 *
 * @author alfredo
 */
public class PanelDevolucion extends javax.swing.JPanel {
	private static Logger logger = Logger.getLogger(PanelDevolucion.class.getName());

	private static DecimalFormat df = new DecimalFormat("$ ###,###,##0.00");
	private static String imagesDir = null;
	/**
	 * Creates new form PanelVenta
	 */
	public PanelDevolucion() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoAlmacen = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelTotal6 = new javax.swing.JLabel();
        codigoBuscar1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelTotal4 = new javax.swing.JLabel();
        codigoBuscar = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalleVentaJTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        labelTotal1 = new javax.swing.JLabel();
        numArt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        labelTotal = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        labelDescuento = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        labelTotal3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleVentaJTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        labelTotal2 = new javax.swing.JLabel();
        numArt1 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        labelTotal5 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        labelTotal7 = new javax.swing.JLabel();
        total2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        terminar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelTotal6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal6.setText("TICKET VENTA :");
        labelTotal6.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel8.add(labelTotal6);

        codigoBuscar1.setColumns(10);
        codigoBuscar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel8.add(codigoBuscar1);

        jButton1.setText("BUSCAR");
        jPanel8.add(jButton1);

        jPanel7.add(jPanel8);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelTotal4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal4.setText("PRODUCTO :");
        labelTotal4.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(labelTotal4);

        codigoBuscar.setColumns(10);
        codigoBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(codigoBuscar);

        jPanel7.add(jPanel2);

        add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel17.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELEMENTOS DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel13.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 200));

        detalleVentaJTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        detalleVentaJTable.setRowHeight(28);
        jScrollPane1.setViewportView(detalleVentaJTable);

        jPanel13.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelTotal1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal1.setText("# ART. :");
        jPanel12.add(labelTotal1);

        numArt.setEditable(false);
        numArt.setColumns(4);
        numArt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numArt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel12.add(numArt);

        jPanel14.add(jPanel12);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal.setText("Subtotal :");
        jPanel6.add(labelTotal);

        subtotal.setEditable(false);
        subtotal.setColumns(6);
        subtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel6.add(subtotal);

        jPanel14.add(jPanel6);

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        labelDescuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDescuento.setText("-Descuento :");
        jPanel15.add(labelDescuento);

        descuento.setEditable(false);
        descuento.setColumns(6);
        descuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel15.add(descuento);

        jPanel1.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        labelTotal3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal3.setText("Total :");
        jPanel16.add(labelTotal3);

        total.setEditable(false);
        total.setColumns(6);
        total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel16.add(total);

        jPanel1.add(jPanel16);

        jPanel13.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel17.add(jPanel13);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELEMENTOS DEVUELTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel19.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 200));

        detalleVentaJTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        detalleVentaJTable1.setRowHeight(28);
        jScrollPane2.setViewportView(detalleVentaJTable1);

        jPanel19.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelTotal2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal2.setText("# ART. :");
        jPanel21.add(labelTotal2);

        numArt1.setEditable(false);
        numArt1.setColumns(4);
        numArt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numArt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel21.add(numArt1);

        jPanel20.add(jPanel21);

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        labelTotal5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal5.setText("Total :");
        jPanel23.add(labelTotal5);

        total1.setEditable(false);
        total1.setColumns(6);
        total1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel23.add(total1);

        jPanel20.add(jPanel23);

        jPanel5.add(jPanel20);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        labelTotal7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal7.setText("Motivo :");
        jPanel18.add(labelTotal7);

        total2.setEditable(false);
        total2.setColumns(15);
        total2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel18.add(total2);

        jPanel5.add(jPanel18);

        jPanel19.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel17.add(jPanel19);

        add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        terminar.setText("TERMINAR DEVOLUCIÓN [ F1 ]");
        jPanel4.add(terminar);

        cancelar.setText("CANCELAR [ F12 ]");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel4.add(cancelar);

        jPanel3.add(jPanel4);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigoBuscar;
    private javax.swing.JTextField codigoBuscar1;
    private javax.swing.JTextField descuento;
    private javax.swing.JTable detalleVentaJTable;
    private javax.swing.JTable detalleVentaJTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel labelTotal2;
    private javax.swing.JLabel labelTotal3;
    private javax.swing.JLabel labelTotal4;
    private javax.swing.JLabel labelTotal5;
    private javax.swing.JLabel labelTotal6;
    private javax.swing.JLabel labelTotal7;
    private javax.swing.JTextField numArt;
    private javax.swing.JTextField numArt1;
    private javax.swing.JTextField subtotal;
    private javax.swing.JButton terminar;
    private javax.swing.ButtonGroup tipoAlmacen;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    // End of variables declaration//GEN-END:variables


	/**
	 * @return the cancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the codigoBuscar
	 */
	public javax.swing.JTextField getCodigoBuscar() {
		return codigoBuscar;
	}

	/**
	 * @return the detalleVentaJTable
	 */
	public javax.swing.JTable getDetalleVentaJTable() {
		return detalleVentaJTable;
	}

	/**
	 * @return the terminar
	 */
	public javax.swing.JButton getTerminar() {
		return terminar;
	}

	/**
	 * @return the total
	 */
	public javax.swing.JTextField getTotal() {
		return total;
	}

	public JTextField getSubtotal() {
		return subtotal;
	}

	public JTextField getDescuento() {
		return descuento;
	}

	public JLabel getLabelDescuento() {
		return labelDescuento;
	}

	public ButtonGroup getTipoAlmacen() {
		return tipoAlmacen;
	}
	
	public JTextField getNumArt() {
		return numArt;
	}

	@Override
	public void setFont(Font font) {
		super.setFont(font); //To change body of generated methods, choose Tools | Templates.
		if(codigoBuscar!=null) {
			codigoBuscar.setFont(font);
			labelTotal.setFont(font);
			total.setFont(font);
			terminar.setFont(font);
			cancelar.setFont(font);
			detalleVentaJTable.setFont(font);
			detalleVentaJTable.setRowHeight(font.getSize()*2);
		}
	}

}
