/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pmarlen.caja.view;

import com.pmarlen.rest.dto.P;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author alfredo
 */
public class ProductoCellRender extends javax.swing.JPanel implements TableCellRenderer {
	private static DecimalFormat df = new DecimalFormat("$ ###,###,##0.00");
	private Color bgc;
	private Color fgc;
	private Color sbgc; 
	private Color sfgc;

	public void setColors(Color bgc, Color fgc, Color sbgc, Color sfgc) {
		this.bgc = bgc;
		this.fgc = fgc;
		this.sbgc = sbgc;
		this.sfgc = sfgc;		
	}
	
	
	/**
	 * Creates new form ProductoCellRender
	 */
	public ProductoCellRender() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        nombreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        nombreLabel.setText("NOMBRE");
        add(nombreLabel, java.awt.BorderLayout.CENTER);

        descripcionLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        descripcionLabel.setText("PRESENTACIÓN");
        add(descripcionLabel, java.awt.BorderLayout.SOUTH);

        precioLabel.setText("CONTENIDO");
        add(precioLabel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel precioLabel;
    // End of variables declaration//GEN-END:variables

	@Override
	public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
		ProductoCellRender pcr= new ProductoCellRender();
		
		P p=(P)value;
		
		pcr.nombreLabel.setText(p.getN().toUpperCase());
		pcr.descripcionLabel.setText(p.getP().toUpperCase());
		//pcr.precioLabel.setText(df.format(p.getA1p()));
		pcr.precioLabel.setText(p.getC()+p.getUm());
		
		if(isSelected){			
			pcr.setBackground(sbgc!=null?sbgc:Color.MAGENTA);
			pcr.setForeground(sfgc!=null?sbgc:Color.BLACK);			
		} else {
			pcr.setBackground(bgc!=null?bgc:Color.WHITE);
			pcr.setForeground(fgc!=null?bgc:Color.BLACK);
		}
		if(hasFocus){			
			pcr.setBorder(new LineBorder(sbgc!=null?sbgc:Color.MAGENTA, 1, false));
		}
		
		return pcr;
	}
}
