/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pmarlen.caja.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author alfredo
 */
public class TerminarVentaDlg extends javax.swing.JDialog {

	/**
	 * Creates new form TerminarVentaDlg
	 */
	public TerminarVentaDlg(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        metodoDePagoLblImg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cleinteNombre = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        metodoDePago = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        recibido = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        calcularCambio = new javax.swing.JButton();
        cambio = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cargo = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        autorizacion = new javax.swing.JTextField();
        terminalTarjeta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TERMINAR VENTA");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(305, 250));
        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        metodoDePagoLblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        metodoDePagoLblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MetodoPago_Efectivo.png"))); // NOI18N
        jPanel7.add(metodoDePagoLblImg);

        jPanel1.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.GridLayout(9, 1));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CLIENTE :");
        jLabel4.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel8.add(jLabel4);

        cleinteNombre.setEditable(false);
        cleinteNombre.setColumns(15);
        cleinteNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cleinteNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel8.add(cleinteNombre);

        jPanel6.add(jPanel8);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("MÉTODO DE PAGO :");
        jLabel6.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel10.add(jLabel6);

        metodoDePago.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel10.add(metodoDePago);

        jPanel6.add(jPanel10);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("SUBTOTAL :");
        jLabel1.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel3.add(jLabel1);

        subtotal.setEditable(false);
        subtotal.setColumns(6);
        subtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(subtotal);

        jPanel6.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DESCUENTO :");
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel4.add(jLabel2);

        descuento.setEditable(false);
        descuento.setColumns(6);
        descuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(descuento);

        jPanel6.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TOTAL :");
        jLabel3.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel5.add(jLabel3);

        total.setEditable(false);
        total.setColumns(6);
        total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(total);

        jPanel6.add(jPanel5);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("EFECTIVO RECIB.:");
        jLabel8.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel14.add(jLabel8);

        recibido.setColumns(6);
        recibido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recibido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel14.add(recibido);

        jPanel6.add(jPanel14);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel13.setPreferredSize(new java.awt.Dimension(280, 36));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        calcularCambio.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        calcularCambio.setText("CAMBIO :");
        calcularCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcularCambio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calcularCambio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel13.add(calcularCambio);

        jPanel12.add(jPanel13);

        cambio.setEditable(false);
        cambio.setColumns(6);
        cambio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 153, 51));
        cambio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel12.add(cambio);

        jPanel6.add(jPanel12);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CARGO A TARJETA :");
        jLabel7.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel9.add(jLabel7);

        cargo.setColumns(6);
        cargo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cargo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel9.add(cargo);

        jPanel6.add(jPanel9);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("NO. AUTORIZACIÓN :");
        jLabel9.setPreferredSize(new java.awt.Dimension(280, 26));
        jPanel11.add(jLabel9);

        autorizacion.setColumns(6);
        autorizacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel11.add(autorizacion);

        terminalTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TerminarlVisaMasterCard.gif"))); // NOI18N
        jPanel11.add(terminalTarjeta);

        jPanel6.add(jPanel11);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        jPanel2.add(aceptar);

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelar.setText("CANCELAR");
        jPanel2.add(cancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(987, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField autorizacion;
    private javax.swing.JButton calcularCambio;
    private javax.swing.JTextField cambio;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField cleinteNombre;
    private javax.swing.JTextField descuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox metodoDePago;
    private javax.swing.JLabel metodoDePagoLblImg;
    private javax.swing.JTextField recibido;
    private javax.swing.JTextField subtotal;
    private javax.swing.JLabel terminalTarjeta;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the cambio
	 */
	public javax.swing.JTextField getCambio() {
		return cambio;
	}

	public JTextField getCleinteNombre() {
		return cleinteNombre;
	}

	/**
	 * @return the descuento
	 */
	public javax.swing.JTextField getDescuento() {
		return descuento;
	}


	/**
	 * @return the metodoDePago
	 */
	public javax.swing.JComboBox getMetodoDePago() {
		return metodoDePago;
	}

	/**
	 * @return the recibido
	 */
	public javax.swing.JTextField getRecibido() {
		return recibido;
	}

	/**
	 * @return the subtotal
	 */
	public javax.swing.JTextField getSubtotal() {
		return subtotal;
	}

	/**
	 * @return the total
	 */
	public javax.swing.JTextField getTotal() {
		return total;
	}

	public JButton getAceptar() {
		return aceptar;
	}

	public JButton getCancelar() {
		return cancelar;
	}

	public JTextField getCargo() {
		return cargo;
	}

	public JTextField getAutorizacion() {
		return autorizacion;
	}

	public JLabel getMetodoDePagoLblImg() {
		return metodoDePagoLblImg;
	}

	public JButton getCalcularCambio() {
		return calcularCambio;
	}

	public JLabel getTerminalTarjeta() {
		return terminalTarjeta;
	}
	
}
