DROP TABLE IF EXISTS EVENTO_SINCRONIZACION;

INSERT INTO METODO_DE_PAGO VALUES (8,'EFECTIVO + TARJETA');

ALTER TABLE SUCURSAL ADD COLUMN CLAVE VARCHAR(16) NULL;

UPDATE SUCURSAL SET CLAVE='PMAE', NOMBRE='PERFUMERIA MARLEN S.A. DE C.V. ALMACEN ESPERANZA',          DIRECCION='CALLE ORQUIDEAS MZ. 5, LT. 6, COL. LA ESPERANZA, MPO. DE TECAMAC, EDO. DE MEX. C.P. 55748',                    TELEFONOS='55-3872-3953' WHERE ID=1;
UPDATE SUCURSAL SET CLAVE='PMS1', NOMBRE='PERFUMERIA MARLEN S.A. DE C.V. SUCURSAL SN. MARTIN',        DIRECCION='CALLE FRANCISCO VILLA MZ. 98, LT.3, NO. 121, COL. SAN MARTIN AZCATEPEC, MPO. TECAMAC. EDO. DE MÉX. C.P. 55740',TELEFONOS='55-5936-7894' WHERE ID=2;

INSERT INTO SUCURSAL( ID,ID_PADRE,CLAVE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  3,       1,'PMS2','PERFUMERIA MARLEN S.A. DE C.V. SUCURSAL TECAMÁC'    ,'CALLE FELIPE VILLANUEVA  NO. 30, LOCAL A, COL. CENTRO, MUNICIPIO DE TECAMAC, EDO. DE MÉX. C.P. 554740'                   ,'55-5934-3788' ,'SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL);
INSERT INTO SUCURSAL( ID,ID_PADRE,CLAVE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  4,       1,'PMS3','PERFUMERIA MARLEN S.A. DE C.V. SUCURSAL OJO DE AGUA','CALZADA DE LA HACIENDA NO. 20, MZ. 57, LOCAL 1, COL. HACIENDA OJO DE AGUA, MUNICIPIO DE TECAMAC, EDO. DE MÉX. C.P. 55760','55-5938-3573','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL);
INSERT INTO SUCURSAL( ID,ID_PADRE,CLAVE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  5,       1,'PMS4','PERFUMERIA MARLEN S.A. DE C.V. ALMACÉN TECÁMAC'     ,'CALLE REFORMA NO. 2, LOCAL 1 COL. CENTRO DE REYES ACOZAC, PLAZA COMERCIAL  “PASAJE REFORMA” MUNICIPIO DE TECÁMAC, ESTADO DE MÉXICO, C.P.L 55755'  ,'55-5936-2597','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL);
INSERT INTO SUCURSAL( ID,ID_PADRE,CLAVE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  6,    NULL,'PMCD','PERFUMERIA MARLEN S.A. DE C.V. CENTRO DE DISTRIBUCIÓN TECAMAC'     ,'CALLE CENTENARIO DE LA EDUCACION MZ. 24, LT. 10, COL. CENTRO, MPO. TECAMAC, EDO. DE MEX. C.P. 55740'    ,'55-5936-2597','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL);

UPDATE SUCURSAL SET DESCUENTO_MAYOREO_HABILITADO=1 WHERE ID IN(2,3,4,5);
UPDATE SUCURSAL SET DESCUENTO_MAYOREO_HABILITADO=0 WHERE ID IN(1,6);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 7, 1, 3);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 8, 2, 3);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 9, 3, 3);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (10, 1, 4);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (11, 2, 4);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (12, 3, 4);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (13, 1, 5);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (14, 2, 5);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (15, 3, 5);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (16, 1, 6);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (17, 2, 6);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (18, 3, 6);

DROP TABLE CORTE_CAJA;

CREATE TABLE     CORTE_CAJA     (
  ID               INTEGER     (10)  NOT NULL AUTO_INCREMENT ,
  TIPO_EVENTO      INTEGER     (1)   NOT NULL,
  FECHA            TIMESTAMP         NOT NULL ,
  SUCURSAL_ID      INTEGER     (10)  NOT NULL ,
  CAJA             INTEGER     (3)   NULL ,
  USUARIO_EMAIL    VARCHAR     (64)  NULL ,
  SALDO_INICIAL    DOUBLE            NULL ,
  SALDO_FINAL      DOUBLE            NULL ,
  USUARIO_AUTORIZO VARCHAR     (64)  NULL ,
  COMENTARIOS      VARCHAR     (255) NULL ,
  PRIMARY KEY (    ID    )
)ENGINE=InnoDB;

ALTER TABLE CORTE_CAJA ADD  CONSTRAINT FOREIGN KEY (USUARIO_EMAIL   ) REFERENCES USUARIO(EMAIL);
ALTER TABLE CORTE_CAJA ADD  CONSTRAINT FOREIGN KEY (USUARIO_AUTORIZO) REFERENCES USUARIO(EMAIL);
