INSERT INTO SUCURSAL( ID,ID_PADRE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  3,       1,'PERFUMERIA MARLEN S.A. DE C.V. SUCURSAL TECÁMAC'    ,'TECÁMAC CENTRO'   ,'5500000000','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL                        );
INSERT INTO SUCURSAL( ID,ID_PADRE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  4,       1,'PERFUMERIA MARLEN S.A. DE C.V. SUCURSAL OJO DE AGUA','OJO DE AGUA'      ,'5500000000','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL                        );
INSERT INTO SUCURSAL( ID,ID_PADRE,NOMBRE                                               ,DIRECCION          ,TELEFONOS   ,USUARIO_SICOFI,PASSWORD_SICOFI,SERIE_SICOFI,COMENTARIOS,DESCUENTO_MAYOREO_HABILITADO)
              VALUES(  5,       1,'PERFUMERIA MARLEN S.A. DE C.V. ALMACÉN TECÁMAC'     ,'TECÁMAC NUEVA'    ,'5500000000','SINUSUARIO'  ,'SINPASSWORD'  ,'XXX'  ,NULL       ,NULL                        );

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 7, 1, 3);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 8, 2, 3);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES ( 9, 3, 3);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (10, 1, 4);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (11, 2, 4);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (12, 3, 4);

INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (13, 1, 5);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (14, 2, 5);
INSERT INTO ALMACEN (ID , TIPO_ALMACEN , SUCURSAL_ID) VALUES (15, 3, 5);

