SELECT	ES.TOTAL ,ES.ID ES_ID,ES.TIPO_MOV,ES.SUCURSAL_ID,ES.ESTADO_ID,ES.FECHA_CREO,ES.USUARIO_EMAIL_CREO,ES.CLIENTE_ID,ES.FORMA_DE_PAGO_ID,ES.METODO_DE_PAGO_ID,ES.FACTOR_IVA,ES.COMENTARIOS,ES.CFD_ID,ES.NUMERO_TICKET,ES.CAJA,ES.IMPORTE_RECIBIDO,ES.APROBACION_VISA_MASTERCARD,ES.PORCENTAJE_DESCUENTO_CALCULADO,ES.PORCENTAJE_DESCUENTO_EXTRA,ES.CONDICIONES_DE_PAGO,ES.NUM_DE_CUENTA,ES.AUTORIZA_DESCUENTO,ES.SUB_TOTAL_1RA,ES.SUB_TOTAL_OPO,ES.SUB_TOTAL_REG,ES.TOTAL,ES.PEDIDO_SUCURSAL,TOT_PRODS,ES.ES_ID_DEV,ES.ES_ID_TRA_ORI,ES.SUCURSAL_ID_TRA_ORI,ES.SUCURSAL_ID_TRA_DES,
CFD.ID AS CFD_ID,
S.NOMBRE AS SUCURSAL_NOMBRE,
E.DESCRIPCION AS E_DESCRIPCION,
U.NOMBRE_COMPLETO AS U_NOMBRE_COMPLETO,
C.RFC AS C_RFC,
C.RAZON_SOCIAL AS C_RAZON_SOCIAL,
C.NOMBRE_ESTABLECIMIENTO AS C_NOMBRE_ESTABLECIMIENTO,
FP.DESCRIPCION AS FP_DESCRIPCION,
MP.DESCRIPCION AS MP_DESCRIPCION,
CFD.NUM_CFD AS CFD_NUM_CFD,
CFD.CALLING_ERROR_RESULT AS CFD_CALLING_ERROR_RESULT,
COUNT(1) NUM_ELEMENTOS, 
SUM(ESD.CANTIDAD * ESD.PRECIO_VENTA) AS IMPORTE_BRUTO, 
ESE.FECHA AS FECHA_ACTUALIZO, 
ESE.USUARIO_EMAIL AS USUARIO_ACTUALIZO,
S1.NOMBRE AS S1_NOMBRE,
S2.NOMBRE AS S2_NOMBRE,
S1.CLAVE  AS S1_CLAVE,
S2.CLAVE  AS S2_CLAVE
 FROM       ENTRADA_SALIDA_ESTADO  ESE,
          ENTRADA_SALIDA_DETALLE ESD,
          ENTRADA_SALIDA         ES
LEFT JOIN CFD            CFD ON ES.CFD_ID      = CFD.ID
LEFT JOIN SUCURSAL       S   ON ES.SUCURSAL_ID       = S.ID
LEFT JOIN SUCURSAL       S1  ON ES.SUCURSAL_ID_TRA_ORI = S1.ID
LEFT JOIN SUCURSAL       S2  ON ES.SUCURSAL_ID_TRA_DES = S2.ID
LEFT JOIN ESTADO         E   ON ES.ESTADO_ID         = E.ID
LEFT JOIN USUARIO        U   ON ES.USUARIO_EMAIL_CREO= U.EMAIL
LEFT JOIN CLIENTE        C   ON ES.CLIENTE_ID        = C.ID
LEFT JOIN FORMA_DE_PAGO  FP  ON ES.FORMA_DE_PAGO_ID  = FP.ID
LEFT JOIN METODO_DE_PAGO MP  ON ES.METODO_DE_PAGO_ID = MP.ID
WHERE     1=1
AND       ES.ESTADO_ID >  4
AND       ES.ID        = ESD.ENTRADA_SALIDA_ID
AND       ES.ID        = ESE.ENTRADA_SALIDA_ID
AND       ES.ESTADO_ID = ESE.ESTADO_ID
AND       ES.TIPO_MOV  = ?
AND       ES.SUCURSAL_ID= ?
 GROUP BY  ESD.ENTRADA_SALIDA_ID
 ORDER BY ES.ID DESC 


SELECT    ES.ID ES_ID,ES.CAJA,ES.TIPO_MOV,ES.SUCURSAL_ID,ES.ESTADO_ID,ES.FECHA_CREO,ES.USUARIO_EMAIL_CREO,ES.CLIENTE_ID,ES.NUMERO_TICKET
FROM      ENTRADA_SALIDA ES
WHERE     1=1
AND       ES.ESTADO_ID >  4
AND       ES.TIPO_MOV  = 30
AND       ES.SUCURSAL_ID= 1
 ORDER BY ES.ID DESC
LIMIT     5,5;

SELECT    ES.ID ES_ID,ES.CAJA,ES.TIPO_MOV,ES.SUCURSAL_ID,ES.ESTADO_ID,ES.FECHA_CREO,ES.USUARIO_EMAIL_CREO,ES.CLIENTE_ID,ES.NUMERO_TICKET
FROM      ENTRADA_SALIDA ES
WHERE     1=1
AND       ES.ESTADO_ID >  4
AND       ES.TIPO_MOV  = 30
AND       ES.SUCURSAL_ID= 1
 ORDER BY ES.ID DESC
LIMIT     5,10;

SELECT    COUNT(*) AS N
FROM      ENTRADA_SALIDA ES
WHERE     1=1
AND       ES.ESTADO_ID >  4
AND       ES.TIPO_MOV  = 30
AND       ES.SUCURSAL_ID= 1
 ORDER BY ES.ID DESC
LIMIT     5,10;

