-- ============================= CREACION DEL ESQUEMA DE LA BASE DE DATOS ====================
DROP DATABASE IF EXISTS PM_XCD;
CREATE DATABASE PM_XCD;
USE PM_XCD;
-- ============================= CREACION DEL ESQUEMA DE LA BASE DE DATOS ====================
CREATE TABLE PRODUCTO (
	CODIGO					VARCHAR (64)	NOT NULL ,
	INDUSTRIA				VARCHAR (255)	NOT NULL ,
	LINEA					VARCHAR (255)	NOT NULL ,
	MARCA					VARCHAR (255)	NOT NULL ,	
	NOMBRE					VARCHAR (255)	NOT NULL ,
	PRESENTACION			VARCHAR (255)	NOT NULL ,
	CONTENIDO				INTEGER			NOT NULL ,
	UNIDAD_MEDIDA			VARCHAR (16)	NOT NULL ,
	UNIDADES_X_CAJA			INTEGER			NOT NULL ,
	COSTO					DOUBLE			NOT NULL ,
	PRECIO_VENTA			DOUBLE			NOT NULL ,
	PRECIO_VENTA_REGALIAS	DOUBLE			NOT NULL ,
	EXISTENCIA				INTEGER			NOT NULL ,
	EXISTENCIA_REGALIAS		INTEGER			NOT NULL ,
	
	PRIMARY KEY (CODIGO)
)ENGINE=InnoDB;

-- ===============================================================================
CREATE TABLE PEDIDO_VENTA (
	ID			INTEGER	 NOT NULL AUTOINCREMENT,
	ESTADO		INTEGER	 (10)	 NOT NULL ,
	FECHA_ACTUALIZACION		DATETIME		 NOT NULL ,
	USUARIO_EMAIL		VARCHAR	 (64)	 NOT NULL ,
	CLIENTE_ID		INTEGER	 (10)	 ,
	FORMA_DE_PAGO_ID		INTEGER	 (10)	 ,

	PRIMARY KEY (ID)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE PEDIDO_VENTA_DETALLE (
	ID				INTEGER	 NOT NULL AUTOINCREMENT ,
	VENTA_ID		INTEGER	 NOT NULL ,
	PRODUCTO_CODIGO	VARCHAR (64)	 NOT NULL,
	CANTIDAD		INTEGER	 NOT NULL ,
	PRECIO_VENTA	DOUBLE	 NOT NULL ,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE CONFIGURACION_SISTEMA (
	ID				VARCHAR (32)	 NOT NULL ,
	VALOR			VARCHAR (128)	 NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE FORMA_DE_PAGO (
	ID		INTEGER	 (10)	 NOT NULL AUTO_INCREMENT ,
	DESCRIPCION		VARCHAR	 (255)	 NOT NULL ,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

-- ===============================================================================
CREATE TABLE CLIENTE (
	ID		INTEGER	 (10)	 NOT NULL AUTO_INCREMENT ,
	RFC		VARCHAR	 (16)	 NOT NULL ,
	RAZON_SOCIAL		VARCHAR	 (128)	 NOT NULL ,
	NOMBRE_ESTABLECIMIENTO		VARCHAR	 (128)	 ,
	CONTACTO		VARCHAR	 (128)	 ,
	TELEFONOS		VARCHAR	 (128)	 ,
	EMAIL		VARCHAR	 (64)	 ,
	OBSERVACIONES		VARCHAR	 (255)	 ,
	DIRECCION		VARCHAR	 (255)	 ,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

-- ===============================================================================
CREATE TABLE CONFIGURACION_SISTEMA (
	LLAVE		VARCHAR	 (128)	 NOT NULL ,
	VALOR		VARCHAR	 (255)	 NOT NULL ,
	PRIMARY KEY (LLAVE)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE USUARIO (
	EMAIL		VARCHAR	 (64)	 NOT NULL ,
	HABILITADO		INTEGER	 (1)	 NOT NULL ,
	NOMBRE_COMPLETO		VARCHAR	 (128)	 NOT NULL ,
	PASSWORD		VARCHAR	 (64)	 NOT NULL ,
	SUCURSAL_ID		INTEGER	 (10)	 ,
	PRIMARY KEY (EMAIL)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE USUARIO_PERFIL (
	EMAIL		VARCHAR	 (64)	 NOT NULL ,
	PERFIL_ID		VARCHAR	 (32)	 NOT NULL ,
	PRIMARY KEY (EMAIL, PERFIL_ID)
)ENGINE=InnoDB;
-- ===============================================================================
CREATE TABLE `SUCURSAL` (
	`ID`		INTEGER	 (10)	 NOT NULL AUTO_INCREMENT ,
	`ID_PADRE`		INTEGER	 (10)	 ,
	`NOMBRE`		VARCHAR	 (128)	 NOT NULL ,
	`DIRECCION`		VARCHAR	 (255)	 ,
	`TELEFONOS`		VARCHAR	 (128)	 ,
	`USUARIO_SICOFI`		VARCHAR	 (64)	 ,
	`PASSWORD_SICOFI`		VARCHAR	 (64)	 ,
	`SERIE_SICOFI`		VARCHAR	 (4)	 ,
	`COMENTARIOS`		VARCHAR	 (255)	 ,
	`DESCUENTO_MAYOREO_HABILITADO`		INTEGER	 (1)	 ,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

-- =================================== CONSTRAINTS ==============================
CREATE PRODUCTO_IDX_1 INDEX ON PRODUCTO (INDUSTRIA);
CREATE PRODUCTO_IDX_2 INDEX ON PRODUCTO (LINEA);
CREATE PRODUCTO_IDX_3 INDEX ON PRODUCTO (MARCA);
CREATE PRODUCTO_IDX_4 INDEX ON PRODUCTO (NOMBRE);
CREATE PRODUCTO_IDX_5 INDEX ON PRODUCTO (PRESENTACION);
CREATE PRODUCTO_IDX_6 INDEX ON PRODUCTO (UNIDAD_MEDIDA);

ALTER TABLE VENTA_DETALLE ADD FOREIGN KEY (PRODUCTO_CODIGO)	REFERENCES PRODUCTO(CODIGO);
ALTER TABLE VENTA_DETALLE ADD FOREIGN KEY (VENTA_ID)	REFERENCES VENTA(ID);
ALTER TABLE `USUARIO_PERFIL` ADD CONSTRAINT FOREIGN KEY (`EMAIL`)	REFERENCES `USUARIO`(`EMAIL`);
ALTER TABLE `USUARIO_PERFIL` ADD CONSTRAINT FOREIGN KEY (`PERFIL_ID`)	REFERENCES `PERFIL`(`ID`);
ALTER TABLE `PEDIDO_VENTA` ADD CONSTRAINT FOREIGN KEY (`USUARIO_EMAIL`)	REFERENCES `USUARIO`(`EMAIL`);
ALTER TABLE `PEDIDO_VENTA` ADD CONSTRAINT FOREIGN KEY (`CLIENTE_ID`)	REFERENCES `CLIENTE`(`ID`);
ALTER TABLE `PEDIDO_VENTA` ADD CONSTRAINT FOREIGN KEY (`FORMA_DE_PAGO_ID`)	REFERENCES `FORMA_DE_PAGO`(`ID`);
ALTER TABLE `SUCURSAL` ADD CONSTRAINT FOREIGN KEY (`ID_PADRE`)	REFERENCES `SUCURSAL`(`ID`);
	