
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DigiFactSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    mx.gob.sat.aerolineas.ObjectFactory.class,
    mx.gob.sat.iedu.ObjectFactory.class,
    mx.gob.sat.ine.ObjectFactory.class,
    mx.gob.sat.leyendasfiscales.ObjectFactory.class,
    mx.gob.sat.notariospublicos.ObjectFactory.class,
    mx.gob.sat.terceros.ObjectFactory.class,
    mx.gob.sat.ventavehiculos.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface DigiFactSoap {


    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33", action = "http://tempuri.org/GeneraCFDIV33")
    @WebResult(name = "GeneraCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33")
    @ResponseWrapper(localName = "GeneraCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33Response")
    public CFDIResponse generaCFDIV33(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponseComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDIV33CPagos", action = "http://tempuri.org/GeneraCFDIV33CPagos")
    @WebResult(name = "GeneraCFDIV33CPagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33CPagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33CPagos")
    @ResponseWrapper(localName = "GeneraCFDIV33CPagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33CPagosResponse")
    public CFDIResponseComplementoDePagos generaCFDIV33CPagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequestComplementoDePago cfdiRequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse
     */
    @WebMethod(operationName = "GeneraCFDINomina12", action = "http://tempuri.org/GeneraCFDINomina12")
    @WebResult(name = "GeneraCFDINomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12")
    @ResponseWrapper(localName = "GeneraCFDINomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12Response")
    public CFDINominaResponse generaCFDINomina12(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest nominarequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse33
     */
    @WebMethod(operationName = "GeneraCFDINomina12V33", action = "http://tempuri.org/GeneraCFDINomina12V33")
    @WebResult(name = "GeneraCFDINomina12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33")
    @ResponseWrapper(localName = "GeneraCFDINomina12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33Response")
    public CFDINominaResponse33 generaCFDINomina12V33(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest33 nominarequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDINominaCancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDINomina12", action = "http://tempuri.org/CancelaCFDINomina12")
    @WebResult(name = "CancelaCFDINomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12")
    @ResponseWrapper(localName = "CancelaCFDINomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12Response")
    public CFDINominaCancelacionResponse cancelaCFDINomina12(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDICancelacionNominaRequest cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDINominaCancelacionResponse33
     */
    @WebMethod(operationName = "CancelaCFDINomina12V33", action = "http://tempuri.org/CancelaCFDINomina12V33")
    @WebResult(name = "CancelaCFDINomina12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINomina12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12V33")
    @ResponseWrapper(localName = "CancelaCFDINomina12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12V33Response")
    public CFDINominaCancelacionResponse33 cancelaCFDINomina12V33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDICancelacionNominaRequest33 cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDIv33CancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDIV33", action = "http://tempuri.org/CancelaCFDIV33")
    @WebResult(name = "CancelaCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33")
    @ResponseWrapper(localName = "CancelaCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33Response")
    public CFDIv33CancelacionResponse cancelaCFDIV33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequest cancelacionrequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior11", action = "http://tempuri.org/GeneraCFDIComerioExterior11")
    @WebResult(name = "GeneraCFDIComerioExterior11Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior11", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior11Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11Response")
    public CFDIComercioExteriorResponse generaCFDIComerioExterior11(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest comerciorequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse33
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior11V33", action = "http://tempuri.org/GeneraCFDIComerioExterior11V33")
    @WebResult(name = "GeneraCFDIComerioExterior11V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior11V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V33")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior11V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V33Response")
    public CFDIComercioExteriorResponse33 generaCFDIComerioExterior11V33(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest33 comerciorequest);

    /**
     * 
     * @param cambiorequest
     * @return
     *     returns org.tempuri.CambiaEstatus33Response
     */
    @WebMethod(operationName = "CambiaEstatusFactura33", action = "http://tempuri.org/CambiaEstatusFactura33")
    @WebResult(name = "CambiaEstatusFactura33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CambiaEstatusFactura33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaEstatusFactura33")
    @ResponseWrapper(localName = "CambiaEstatusFactura33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaEstatusFactura33Response")
    public CambiaEstatus33Response cambiaEstatusFactura33(
        @WebParam(name = "cambiorequest", targetNamespace = "http://tempuri.org/")
        CambiaEstatus33Request cambiorequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponse
     */
    @WebMethod(operationName = "TimbraCFDIPlusV33", action = "http://tempuri.org/TimbraCFDIPlusV33")
    @WebResult(name = "TimbraCFDIPlusV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIPlusV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlusV33")
    @ResponseWrapper(localName = "TimbraCFDIPlusV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlusV33Response")
    public CFDITimbradoPlusReponse timbraCFDIPlusV33(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequest cfdiRequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.Timbradov33CancelacionResponse
     */
    @WebMethod(operationName = "CancelaTFDV33", action = "http://tempuri.org/CancelaTFDV33")
    @WebResult(name = "CancelaTFDV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaTFDV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTFDV33")
    @ResponseWrapper(localName = "CancelaTFDV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTFDV33Response")
    public Timbradov33CancelacionResponse cancelaTFDV33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        Timbradov33CancelacionRequest cancelacionrequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponseComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDPlusV33ComplementoDePagos", action = "http://tempuri.org/GeneraCFDPlusV33ComplementoDePagos")
    @WebResult(name = "GeneraCFDPlusV33ComplementoDePagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDPlusV33ComplementoDePagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV33ComplementoDePagos")
    @ResponseWrapper(localName = "GeneraCFDPlusV33ComplementoDePagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV33ComplementoDePagosResponse")
    public CFDITimbradoPlusReponseComplementoDePagos generaCFDPlusV33ComplementoDePagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequestComplementoDePagos cfdiRequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaResponse
     */
    @WebMethod(operationName = "TimbraCFDINominaPlus12", action = "http://tempuri.org/TimbraCFDINominaPlus12")
    @WebResult(name = "TimbraCFDINominaPlus12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDINominaPlus12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12")
    @ResponseWrapper(localName = "TimbraCFDINominaPlus12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12Response")
    public TimbradoPlusNominaResponse timbraCFDINominaPlus12(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaRequest nominarequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaResponse33
     */
    @WebMethod(operationName = "TimbraCFDINominaPlus12V33", action = "http://tempuri.org/TimbraCFDINominaPlus12V33")
    @WebResult(name = "TimbraCFDINominaPlus12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDINominaPlus12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V33")
    @ResponseWrapper(localName = "TimbraCFDINominaPlus12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V33Response")
    public TimbradoPlusNominaResponse33 timbraCFDINominaPlus12V33(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaRequest33 nominarequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaCancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDINominaPlus12", action = "http://tempuri.org/CancelaCFDINominaPlus12")
    @WebResult(name = "CancelaCFDINominaPlus12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINominaPlus12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12")
    @ResponseWrapper(localName = "CancelaCFDINominaPlus12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12Response")
    public TimbradoPlusNominaCancelacionResponse cancelaCFDINominaPlus12(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        TibradoPlusNominaCancelacioRequest cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaCancelacionResponse33
     */
    @WebMethod(operationName = "CancelaCFDINominaPlus12V33", action = "http://tempuri.org/CancelaCFDINominaPlus12V33")
    @WebResult(name = "CancelaCFDINominaPlus12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINominaPlus12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12V33")
    @ResponseWrapper(localName = "CancelaCFDINominaPlus12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12V33Response")
    public TimbradoPlusNominaCancelacionResponse33 cancelaCFDINominaPlus12V33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        TibradoPlusNominaCancelacioRequest33 cancelacionrequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.TimbradoPlusComercioExteriorResponse
     */
    @WebMethod(operationName = "TimbraCFDIComercioExteriorplus11", action = "http://tempuri.org/TimbraCFDIComercioExteriorplus11")
    @WebResult(name = "TimbraCFDIComercioExteriorplus11Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIComercioExteriorplus11", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIComercioExteriorplus11")
    @ResponseWrapper(localName = "TimbraCFDIComercioExteriorplus11Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIComercioExteriorplus11Response")
    public TimbradoPlusComercioExteriorResponse timbraCFDIComercioExteriorplus11(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusComercioExteriorRequest comerciorequest);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFNominaResponse
     */
    @WebMethod(operationName = "GeneraPDFNomina12", action = "http://tempuri.org/GeneraPDFNomina12")
    @WebResult(name = "GeneraPDFNomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFNomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFNomina12")
    @ResponseWrapper(localName = "GeneraPDFNomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFNomina12Response")
    public PDFNominaResponse generaPDFNomina12(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFNominaRquest pdfrequest);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFCFDIResponse
     */
    @WebMethod(operationName = "GeneraPDFCFDIV33", action = "http://tempuri.org/GeneraPDFCFDIV33")
    @WebResult(name = "GeneraPDFCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33")
    @ResponseWrapper(localName = "GeneraPDFCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33Response")
    public PDFCFDIResponse generaPDFCFDIV33(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFCFDIRquest pdfrequest);

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI33Response
     */
    @WebMethod(operationName = "TimbraCFDIV33", action = "http://tempuri.org/TimbraCFDIV33")
    @WebResult(name = "TimbraCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV33")
    @ResponseWrapper(localName = "TimbraCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV33Response")
    public TimbraCFDI33Response timbraCFDIV33(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI33Request timbraRequest);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TicketResponse
     */
    @WebMethod(operationName = "IntroduceDatosTicketV33", action = "http://tempuri.org/IntroduceDatosTicketV33")
    @WebResult(name = "IntroduceDatosTicketV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceDatosTicketV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV33")
    @ResponseWrapper(localName = "IntroduceDatosTicketV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV33Response")
    public TicketResponse introduceDatosTicketV33(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TicketRequest request);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFTicketResponse
     */
    @WebMethod(operationName = "GeneraPDFTickets", action = "http://tempuri.org/GeneraPDFTickets")
    @WebResult(name = "GeneraPDFTicketsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFTickets", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFTickets")
    @ResponseWrapper(localName = "GeneraPDFTicketsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFTicketsResponse")
    public PDFTicketResponse generaPDFTickets(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFTicketRquest pdfrequest);

    /**
     * 
     * @param validaRequest
     * @return
     *     returns org.tempuri.ValidaCFDI33Response
     */
    @WebMethod(operationName = "ValidaCFDIV33", action = "http://tempuri.org/ValidaCFDIV33")
    @WebResult(name = "ValidaCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidaCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaCFDIV33")
    @ResponseWrapper(localName = "ValidaCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaCFDIV33Response")
    public ValidaCFDI33Response validaCFDIV33(
        @WebParam(name = "validaRequest", targetNamespace = "http://tempuri.org/")
        ValidaCFDI33Request validaRequest);

}
