
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DigiFact", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://cfd.sicofi.com.mx/SicofiWS33/Digifact.asmx?WSDL")
public class DigiFact
    extends Service
{

    private final static URL DIGIFACT_WSDL_LOCATION;
    private final static WebServiceException DIGIFACT_EXCEPTION;
    private final static QName DIGIFACT_QNAME = new QName("http://tempuri.org/", "DigiFact");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cfd.sicofi.com.mx/SicofiWS33/Digifact.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIGIFACT_WSDL_LOCATION = url;
        DIGIFACT_EXCEPTION = e;
    }

    public DigiFact() {
        super(__getWsdlLocation(), DIGIFACT_QNAME);
    }

    public DigiFact(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIGIFACT_QNAME, features);
    }

    public DigiFact(URL wsdlLocation) {
        super(wsdlLocation, DIGIFACT_QNAME);
    }

    public DigiFact(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIGIFACT_QNAME, features);
    }

    public DigiFact(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigiFact(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DigiFactSoap
     */
    @WebEndpoint(name = "DigiFactSoap")
    public DigiFactSoap getDigiFactSoap() {
        return super.getPort(new QName("http://tempuri.org/", "DigiFactSoap"), DigiFactSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigiFactSoap
     */
    @WebEndpoint(name = "DigiFactSoap")
    public DigiFactSoap getDigiFactSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DigiFactSoap"), DigiFactSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DigiFactSoap
     */
    @WebEndpoint(name = "DigiFactSoap12")
    public DigiFactSoap getDigiFactSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "DigiFactSoap12"), DigiFactSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigiFactSoap
     */
    @WebEndpoint(name = "DigiFactSoap12")
    public DigiFactSoap getDigiFactSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DigiFactSoap12"), DigiFactSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIGIFACT_EXCEPTION!= null) {
            throw DIGIFACT_EXCEPTION;
        }
        return DIGIFACT_WSDL_LOCATION;
    }

}
