
package com.pmarlen.digifactws20160707.production;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CFDSoap", targetNamespace = "https://cfd.sicofi.com.mx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CFDSoap {


    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param conceptos
     * @param impuestos
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFD", action = "https://cfd.sicofi.com.mx/GeneraCFD")
    @WebResult(name = "GeneraCFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFD")
    @ResponseWrapper(localName = "GeneraCFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDResponse")
    public String generaCFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param incapacidades
     * @param conceptos
     * @param impuestos
     * @param horasExtras
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @param deducciones
     * @param percepciones
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDINomina", action = "https://cfd.sicofi.com.mx/GeneraCFDINomina")
    @WebResult(name = "GeneraCFDINominaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDINomina", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDINomina")
    @ResponseWrapper(localName = "GeneraCFDINominaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDINominaResponse")
    public String generaCFDINomina(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosNomina datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Empleado receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "Percepciones", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType percepciones,
        @WebParam(name = "Deducciones", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType deducciones,
        @WebParam(name = "Incapacidades", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType incapacidades,
        @WebParam(name = "HorasExtras", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType horasExtras,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param conceptos
     * @param impuestos
     * @param multipleInfo
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDINominaMultiple", action = "https://cfd.sicofi.com.mx/GeneraCFDINominaMultiple")
    @WebResult(name = "GeneraCFDINominaMultipleResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDINominaMultiple", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDINominaMultiple")
    @ResponseWrapper(localName = "GeneraCFDINominaMultipleResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDINominaMultipleResponse")
    public String generaCFDINominaMultiple(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosNomina datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Empleado receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "MultipleInfo", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType multipleInfo,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param conceptos
     * @param impuestos
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDX", action = "https://cfd.sicofi.com.mx/GeneraCFDX")
    @WebResult(name = "GeneraCFDXResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDX", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDX")
    @ResponseWrapper(localName = "GeneraCFDXResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDXResponse")
    public String generaCFDX(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        ObjetoX datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        ObjetoX receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param complemento
     * @param conceptos
     * @param impuestos
     * @param coComplemento
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDDetallista", action = "https://cfd.sicofi.com.mx/GeneraCFDDetallista")
    @WebResult(name = "GeneraCFDDetallistaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDDetallista", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDDetallista")
    @ResponseWrapper(localName = "GeneraCFDDetallistaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFDDetallistaResponse")
    public String generaCFDDetallista(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda,
        @WebParam(name = "Complemento", targetNamespace = "https://cfd.sicofi.com.mx")
        String complemento,
        @WebParam(name = "COComplemento", targetNamespace = "https://cfd.sicofi.com.mx")
        String coComplemento);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param impuesto
     * @param concepto
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFD_1_Concepto", action = "https://cfd.sicofi.com.mx/GeneraCFD_1_Concepto")
    @WebResult(name = "GeneraCFD_1_ConceptoResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFD_1_Concepto", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFD1Concepto")
    @ResponseWrapper(localName = "GeneraCFD_1_ConceptoResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraCFD1ConceptoResponse")
    public String generaCFD1Concepto(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Concepto", targetNamespace = "https://cfd.sicofi.com.mx")
        Concepto concepto,
        @WebParam(name = "Impuesto", targetNamespace = "https://cfd.sicofi.com.mx")
        Impuesto impuesto,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @param statusfact
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CambiaStatusFact", action = "https://cfd.sicofi.com.mx/CambiaStatusFact")
    @WebResult(name = "CambiaStatusFactResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CambiaStatusFact", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CambiaStatusFact")
    @ResponseWrapper(localName = "CambiaStatusFactResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CambiaStatusFactResponse")
    public String cambiaStatusFact(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio,
        @WebParam(name = "statusfact", targetNamespace = "https://cfd.sicofi.com.mx")
        double statusfact);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaCorreoComprobante", action = "https://cfd.sicofi.com.mx/EnviaCorreoComprobante")
    @WebResult(name = "EnviaCorreoComprobanteResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "EnviaCorreoComprobante", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.EnviaCorreoComprobante")
    @ResponseWrapper(localName = "EnviaCorreoComprobanteResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.EnviaCorreoComprobanteResponse")
    public String enviaCorreoComprobante(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio);

    /**
     * 
     * @param datos
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @param statusfact
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CambiaStatusMagna", action = "https://cfd.sicofi.com.mx/CambiaStatusMagna")
    @WebResult(name = "CambiaStatusMagnaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CambiaStatusMagna", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CambiaStatusMagna")
    @ResponseWrapper(localName = "CambiaStatusMagnaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CambiaStatusMagnaResponse")
    public String cambiaStatusMagna(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio,
        @WebParam(name = "statusfact", targetNamespace = "https://cfd.sicofi.com.mx")
        String statusfact,
        @WebParam(name = "datos", targetNamespace = "https://cfd.sicofi.com.mx")
        String datos);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaCFDI", action = "https://cfd.sicofi.com.mx/CancelaCFDI")
    @WebResult(name = "CancelaCFDIResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaCFDI", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaCFDI")
    @ResponseWrapper(localName = "CancelaCFDIResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaCFDIResponse")
    public String cancelaCFDI(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AcuseCancelacion", action = "https://cfd.sicofi.com.mx/AcuseCancelacion")
    @WebResult(name = "AcuseCancelacionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "AcuseCancelacion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.AcuseCancelacion")
    @ResponseWrapper(localName = "AcuseCancelacionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.AcuseCancelacionResponse")
    public String acuseCancelacion(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDF", action = "https://cfd.sicofi.com.mx/GeneraPDF")
    @WebResult(name = "GeneraPDFResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDF", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDF")
    @ResponseWrapper(localName = "GeneraPDFResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFResponse")
    public byte[] generaPDF(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio);

    /**
     * 
     * @param password
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerSeries", action = "https://cfd.sicofi.com.mx/ObtenerSeries")
    @WebResult(name = "ObtenerSeriesResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "ObtenerSeries", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenerSeries")
    @ResponseWrapper(localName = "ObtenerSeriesResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenerSeriesResponse")
    public String obtenerSeries(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "https://cfd.sicofi.com.mx")
        String password);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "Imagen", action = "https://cfd.sicofi.com.mx/Imagen")
    @WebResult(name = "ImagenResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "Imagen", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.Imagen")
    @ResponseWrapper(localName = "ImagenResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ImagenResponse")
    public byte[] imagen(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerXML", action = "https://cfd.sicofi.com.mx/ObtenerXML")
    @WebResult(name = "ObtenerXMLResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "ObtenerXML", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenerXML")
    @ResponseWrapper(localName = "ObtenerXMLResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenerXMLResponse")
    public String obtenerXML(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio);

    /**
     * 
     * @param datosCFD
     * @param conceptos
     * @param impuestos
     * @param fechaCreacion
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @param numeroTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IntroduceDatosTicket", action = "https://cfd.sicofi.com.mx/IntroduceDatosTicket")
    @WebResult(name = "IntroduceDatosTicketResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "IntroduceDatosTicket", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.IntroduceDatosTicket")
    @ResponseWrapper(localName = "IntroduceDatosTicketResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.IntroduceDatosTicketResponse")
    public String introduceDatosTicket(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "NumeroTicket", targetNamespace = "https://cfd.sicofi.com.mx")
        String numeroTicket,
        @WebParam(name = "FechaCreacion", targetNamespace = "https://cfd.sicofi.com.mx")
        String fechaCreacion,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param numeroTicket
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDFTicket", action = "https://cfd.sicofi.com.mx/GeneraPDFTicket")
    @WebResult(name = "GeneraPDFTicketResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDFTicket", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFTicket")
    @ResponseWrapper(localName = "GeneraPDFTicketResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFTicketResponse")
    public byte[] generaPDFTicket(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "NumeroTicket", targetNamespace = "https://cfd.sicofi.com.mx")
        String numeroTicket);

    /**
     * 
     * @param xml
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidaComprobante", action = "https://cfd.sicofi.com.mx/ValidaComprobante")
    @WebResult(name = "ValidaComprobanteResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "ValidaComprobante", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ValidaComprobante")
    @ResponseWrapper(localName = "ValidaComprobanteResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ValidaComprobanteResponse")
    public String validaComprobante(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "xml", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenTimbresDisponibles", action = "https://cfd.sicofi.com.mx/ObtenTimbresDisponibles")
    @WebResult(name = "ObtenTimbresDisponiblesResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "ObtenTimbresDisponibles", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenTimbresDisponibles")
    @ResponseWrapper(localName = "ObtenTimbresDisponiblesResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.ObtenTimbresDisponiblesResponse")
    public String obtenTimbresDisponibles(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena);

    /**
     * 
     * @param xml
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraTFD", action = "https://cfd.sicofi.com.mx/GeneraTFD")
    @WebResult(name = "GeneraTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraTFD")
    @ResponseWrapper(localName = "GeneraTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraTFDResponse")
    public String generaTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "xml", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDFTimbrado", action = "https://cfd.sicofi.com.mx/GeneraPDFTimbrado")
    @WebResult(name = "GeneraPDFTimbradoResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDFTimbrado", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFTimbrado")
    @ResponseWrapper(localName = "GeneraPDFTimbradoResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFTimbradoResponse")
    public byte[] generaPDFTimbrado(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "UUID", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param rfc
     */
    @WebMethod(operationName = "AgregaRFCPermitido", action = "https://cfd.sicofi.com.mx/AgregaRFCPermitido")
    @RequestWrapper(localName = "AgregaRFCPermitido", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.AgregaRFCPermitido")
    @ResponseWrapper(localName = "AgregaRFCPermitidoResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.AgregaRFCPermitidoResponse")
    public void agregaRFCPermitido(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "RFC", targetNamespace = "https://cfd.sicofi.com.mx")
        String rfc);

    /**
     * 
     * @param xml
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraTFDv2", action = "https://cfd.sicofi.com.mx/GeneraTFDv2")
    @WebResult(name = "GeneraTFDv2Result", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraTFDv2", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraTFDv2")
    @ResponseWrapper(localName = "GeneraTFDv2Response", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraTFDv2Response")
    public String generaTFDv2(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "xml", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaTFD", action = "https://cfd.sicofi.com.mx/CancelaTFD")
    @WebResult(name = "CancelaTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaTFD")
    @ResponseWrapper(localName = "CancelaTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaTFDResponse")
    public String cancelaTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param password
     * @param serie
     * @param folio
     * @param sello
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RevisaTimbrePrevio", action = "https://cfd.sicofi.com.mx/RevisaTimbrePrevio")
    @WebResult(name = "RevisaTimbrePrevioResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "RevisaTimbrePrevio", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.RevisaTimbrePrevio")
    @ResponseWrapper(localName = "RevisaTimbrePrevioResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.RevisaTimbrePrevioResponse")
    public String revisaTimbrePrevio(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "https://cfd.sicofi.com.mx")
        String password,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        int folio,
        @WebParam(name = "Sello", targetNamespace = "https://cfd.sicofi.com.mx")
        String sello);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param conceptos
     * @param impuestos
     * @param addenda
     * @param usuario
     * @param contrasena
     * @param emisorTimbre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraCFD", action = "https://cfd.sicofi.com.mx/TimbraCFD")
    @WebResult(name = "TimbraCFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraCFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFD")
    @ResponseWrapper(localName = "TimbraCFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFDResponse")
    public String timbraCFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "EmisorTimbre", targetNamespace = "https://cfd.sicofi.com.mx")
        EmisorTimbrado emisorTimbre,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "Addenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String addenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param incapacidades
     * @param conceptos
     * @param impuestos
     * @param addenda
     * @param horasExtras
     * @param usuario
     * @param contrasena
     * @param emisorTimbre
     * @param deducciones
     * @param percepciones
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraCFDINomina", action = "https://cfd.sicofi.com.mx/TimbraCFDINomina")
    @WebResult(name = "TimbraCFDINominaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraCFDINomina", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFDINomina")
    @ResponseWrapper(localName = "TimbraCFDINominaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFDINominaResponse")
    public String timbraCFDINomina(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "EmisorTimbre", targetNamespace = "https://cfd.sicofi.com.mx")
        EmisorTimbrado emisorTimbre,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosNomina datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Empleado receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "Percepciones", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType percepciones,
        @WebParam(name = "Deducciones", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType deducciones,
        @WebParam(name = "Incapacidades", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType incapacidades,
        @WebParam(name = "HorasExtras", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType horasExtras,
        @WebParam(name = "Addenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String addenda);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param multipleInf
     * @param conceptos
     * @param impuestos
     * @param addenda
     * @param usuario
     * @param contrasena
     * @param emisorTimbre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraCFDINominaMultiple", action = "https://cfd.sicofi.com.mx/TimbraCFDINominaMultiple")
    @WebResult(name = "TimbraCFDINominaMultipleResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraCFDINominaMultiple", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFDINominaMultiple")
    @ResponseWrapper(localName = "TimbraCFDINominaMultipleResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraCFDINominaMultipleResponse")
    public String timbraCFDINominaMultiple(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "EmisorTimbre", targetNamespace = "https://cfd.sicofi.com.mx")
        EmisorTimbrado emisorTimbre,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosNomina datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Empleado receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "MultipleInf", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType multipleInf,
        @WebParam(name = "Addenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String addenda);

    /**
     * 
     * @param password
     * @param xml
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraSectorPrimario", action = "https://cfd.sicofi.com.mx/TimbraSectorPrimario")
    @WebResult(name = "TimbraSectorPrimarioResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraSectorPrimario", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraSectorPrimario")
    @ResponseWrapper(localName = "TimbraSectorPrimarioResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraSectorPrimarioResponse")
    public String timbraSectorPrimario(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "https://cfd.sicofi.com.mx")
        String password,
        @WebParam(name = "XML", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @param anterior
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaTFDSectorPrimario", action = "https://cfd.sicofi.com.mx/CancelaTFDSectorPrimario")
    @WebResult(name = "CancelaTFDSectorPrimarioResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaTFDSectorPrimario", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaTFDSectorPrimario")
    @ResponseWrapper(localName = "CancelaTFDSectorPrimarioResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaTFDSectorPrimarioResponse")
    public String cancelaTFDSectorPrimario(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid,
        @WebParam(name = "Anterior", targetNamespace = "https://cfd.sicofi.com.mx")
        boolean anterior);

    /**
     * 
     * @param datosCFD
     * @param receptor
     * @param conceptos
     * @param impuestos
     * @param usuario
     * @param contrasena
     * @param emisorTimbre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraSectorPrimarioPlus", action = "https://cfd.sicofi.com.mx/TimbraSectorPrimarioPlus")
    @WebResult(name = "TimbraSectorPrimarioPlusResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraSectorPrimarioPlus", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraSectorPrimarioPlus")
    @ResponseWrapper(localName = "TimbraSectorPrimarioPlusResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraSectorPrimarioPlusResponse")
    public String timbraSectorPrimarioPlus(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "EmisorTimbre", targetNamespace = "https://cfd.sicofi.com.mx")
        EmisorTimbrado emisorTimbre,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos);

    /**
     * 
     * @param impuestosRetencion
     * @param receptor
     * @param datos
     * @param complementosRetencion
     * @param xmlAddenda
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraRetencion", action = "https://cfd.sicofi.com.mx/GeneraRetencion")
    @WebResult(name = "GeneraRetencionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraRetencion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraRetencion")
    @ResponseWrapper(localName = "GeneraRetencionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraRetencionResponse")
    public String generaRetencion(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Datos", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosConstanciaRetencion datos,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        ReceptorConstanciaRetencion receptor,
        @WebParam(name = "impuestosRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfImpuestoRetencion impuestosRetencion,
        @WebParam(name = "complementosRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        ComplementosRetenciones complementosRetencion,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param folio
     * @param usuario
     * @param contrasena
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDFConstanciaRetencion", action = "https://cfd.sicofi.com.mx/GeneraPDFConstanciaRetencion")
    @WebResult(name = "GeneraPDFConstanciaRetencionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDFConstanciaRetencion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFConstanciaRetencion")
    @ResponseWrapper(localName = "GeneraPDFConstanciaRetencionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFConstanciaRetencionResponse")
    public byte[] generaPDFConstanciaRetencion(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaConstancia", action = "https://cfd.sicofi.com.mx/CancelaConstancia")
    @WebResult(name = "CancelaConstanciaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaConstancia", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaConstancia")
    @ResponseWrapper(localName = "CancelaConstanciaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaConstanciaResponse")
    public String cancelaConstancia(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param impuestosRetencion
     * @param receptorRetencion
     * @param addenda
     * @param complementosRetencion
     * @param emisorRetencion
     * @param usuario
     * @param contrasena
     * @param datosRetencion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TimbraRetencion", action = "https://cfd.sicofi.com.mx/TimbraRetencion")
    @WebResult(name = "TimbraRetencionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TimbraRetencion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraRetencion")
    @ResponseWrapper(localName = "TimbraRetencionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TimbraRetencionResponse")
    public String timbraRetencion(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "datosRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosRetencion datosRetencion,
        @WebParam(name = "emisorRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        EmisorRetencion emisorRetencion,
        @WebParam(name = "receptorRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        ReceptorRetencion receptorRetencion,
        @WebParam(name = "impuestosRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfImpuestoRetencion impuestosRetencion,
        @WebParam(name = "complementosRetencion", targetNamespace = "https://cfd.sicofi.com.mx")
        ComplementosRetenciones complementosRetencion,
        @WebParam(name = "Addenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String addenda);

    /**
     * 
     * @param xml
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraRTFD", action = "https://cfd.sicofi.com.mx/GeneraRTFD")
    @WebResult(name = "GeneraRTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraRTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraRTFD")
    @ResponseWrapper(localName = "GeneraRTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraRTFDResponse")
    public String generaRTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "xml", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDFRetencionTimbrado", action = "https://cfd.sicofi.com.mx/GeneraPDFRetencionTimbrado")
    @WebResult(name = "GeneraPDFRetencionTimbradoResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDFRetencionTimbrado", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFRetencionTimbrado")
    @ResponseWrapper(localName = "GeneraPDFRetencionTimbradoResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.GeneraPDFRetencionTimbradoResponse")
    public byte[] generaPDFRetencionTimbrado(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "UUID", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaRTFD", action = "https://cfd.sicofi.com.mx/CancelaRTFD")
    @WebResult(name = "CancelaRTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaRTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaRTFD")
    @ResponseWrapper(localName = "CancelaRTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.CancelaRTFDResponse")
    public String cancelaRTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param datos
     * @param usuario
     * @param contrasena
     * @param key
     * @return
     *     returns com.pmarlen.digifactws20160707.production.DescargaPDFResponse
     */
    @WebMethod(operationName = "DescargaPDFM", action = "https://cfd.sicofi.com.mx/DescargaPDFM")
    @WebResult(name = "DescargaPDFMResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "DescargaPDFM", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.DescargaPDFM")
    @ResponseWrapper(localName = "DescargaPDFMResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.DescargaPDFMResponse")
    public DescargaPDFResponse descargaPDFM(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Datos", targetNamespace = "https://cfd.sicofi.com.mx")
        DescargaPDFS datos,
        @WebParam(name = "Key", targetNamespace = "https://cfd.sicofi.com.mx")
        String key);

    /**
     * 
     * @param parametro1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "https://cfd.sicofi.com.mx/Ping")
    @WebResult(name = "PingResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "Ping", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.PingResponse")
    public String ping(
        @WebParam(name = "parametro1", targetNamespace = "https://cfd.sicofi.com.mx")
        String parametro1);

    /**
     * 
     * @param descripcion
     * @param percepcion
     * @param incapacidad
     * @param datosnomina
     * @param horaextra
     * @param parametro1
     * @param deduccion
     * @param mercancia
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestConexion", action = "https://cfd.sicofi.com.mx/TestConexion")
    @WebResult(name = "TestConexionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "TestConexion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TestConexion")
    @ResponseWrapper(localName = "TestConexionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws20160707.production.TestConexionResponse")
    public String testConexion(
        @WebParam(name = "parametro1", targetNamespace = "https://cfd.sicofi.com.mx")
        String parametro1,
        @WebParam(name = "percepcion", targetNamespace = "https://cfd.sicofi.com.mx")
        Percepcion percepcion,
        @WebParam(name = "deduccion", targetNamespace = "https://cfd.sicofi.com.mx")
        Deduccion deduccion,
        @WebParam(name = "incapacidad", targetNamespace = "https://cfd.sicofi.com.mx")
        Incapacidad incapacidad,
        @WebParam(name = "horaextra", targetNamespace = "https://cfd.sicofi.com.mx")
        HoraExtra horaextra,
        @WebParam(name = "datosnomina", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrDatosNom datosnomina,
        @WebParam(name = "mercancia", targetNamespace = "https://cfd.sicofi.com.mx")
        Mercancia mercancia,
        @WebParam(name = "Descripcion", targetNamespace = "https://cfd.sicofi.com.mx")
        DescripcionEspecifica descripcion);

}
