
package com.pmarlen.digifactws2018.production;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CFD", targetNamespace = "https://cfd.sicofi.com.mx", wsdlLocation = "https://cfd.sicofi.com.mx/sicofiWSv2/cfd.asmx?WSDL")
public class CFD
    extends Service
{

    private final static URL CFD_WSDL_LOCATION;
    private final static WebServiceException CFD_EXCEPTION;
    private final static QName CFD_QNAME = new QName("https://cfd.sicofi.com.mx", "CFD");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cfd.sicofi.com.mx/sicofiWSv2/cfd.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CFD_WSDL_LOCATION = url;
        CFD_EXCEPTION = e;
    }

    public CFD() {
        super(__getWsdlLocation(), CFD_QNAME);
    }

    public CFD(WebServiceFeature... features) {
        super(__getWsdlLocation(), CFD_QNAME, features);
    }

    public CFD(URL wsdlLocation) {
        super(wsdlLocation, CFD_QNAME);
    }

    public CFD(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CFD_QNAME, features);
    }

    public CFD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CFD(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap")
    public CFDSoap getCFDSoap() {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap"), CFDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap")
    public CFDSoap getCFDSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap"), CFDSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap12")
    public CFDSoap getCFDSoap12() {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap12"), CFDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap12")
    public CFDSoap getCFDSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap12"), CFDSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CFD_EXCEPTION!= null) {
            throw CFD_EXCEPTION;
        }
        return CFD_WSDL_LOCATION;
    }

}
