SELECT PV.ID,PV.FORMA_DE_PAGO_ID,PV.USUARIO_ID,PV.ALMACEN_ID,PV.FACTORIVA,PV.COMENTARIOS,PV.DESCUENTO_APLICADO,PVD.PRODUCTO_ID,P.CODIGO_BARRAS,PVE.ESTADO_ID,PVE.FECHA
FROM   PEDIDO_VENTA PV,PEDIDO_VENTA_DETALLE PVD,PEDIDO_VENTA_ESTADO PVE,PRODUCTO P
WHERE  1=1
AND    PV.ID=PVD.PEDIDO_VENTA_ID
AND    PV.ID=PVE.PEDIDO_VENTA_ID
AND    PVD.PRODUCTO_ID=P.ID
AND    PV.ID>175374340;

SELECT PV.ID,PVE.ESTADO_ID,PVE.FECHA,PV.FORMA_DE_PAGO_ID,PV.USUARIO_ID,PV.ALMACEN_ID,PV.FACTORIVA,PV.COMENTARIOS,PV.DESCUENTO_APLICADO,PVD.CANTIDAD,P.CODIGO_BARRAS,PVD.PRECIO_VENTA
FROM   PEDIDO_VENTA PV,PEDIDO_VENTA_DETALLE PVD,PEDIDO_VENTA_ESTADO PVE,PRODUCTO P
WHERE  1=1
AND    PV.ID=PVD.PEDIDO_VENTA_ID
AND    PV.ID=PVE.PEDIDO_VENTA_ID
AND    PVD.PRODUCTO_ID=P.ID
ORDER BY PVE.FECHA;

AND    PV.ID=175374347;
