SELECT PV.ID,PV.FORMA_DE_PAGO_ID,PV.USUARIO_ID,PV.ALMACEN_ID,PV.FACTORIVA,PV.COMENTARIOS,PV.DESCUENTO_APLICADO,PVD.PRODUCTO_ID,P.CODIGO_BARRAS,PVE.ESTADO_ID,PVE.FECHA
FROM   PEDIDO_VENTA PV,PEDIDO_VENTA_DETALLE PVD,PEDIDO_VENTA_ESTADO PVE,PRODUCTO P
WHERE  1=1
AND    PV.ID=PVD.PEDIDO_VENTA_ID
AND    PV.ID=PVE.PEDIDO_VENTA_ID
AND    PVD.PRODUCTO_ID=P.ID
AND    PV.ID>175374340;

SELECT PV.ID,PVE.ESTADO_ID,PVE.FECHA,PV.FORMA_DE_PAGO_ID,PV.USUARIO_ID,A.TIPO_ALMACEN,PV.FACTORIVA,PV.COMENTARIOS,PV.DESCUENTO_APLICADO,PVD.CANTIDAD,P.CODIGO_BARRAS,PVD.PRECIO_VENTA
FROM   PEDIDO_VENTA PV,PEDIDO_VENTA_DETALLE PVD,PEDIDO_VENTA_ESTADO PVE,PRODUCTO P,ALMACEN A
WHERE  1=1
AND    PV.ID=PVD.PEDIDO_VENTA_ID
AND    PV.ID=PVE.PEDIDO_VENTA_ID
AND    PVD.PRODUCTO_ID=P.ID
AND    PV.ALMACEN_ID=A.ID
ORDER BY PVE.FECHA;

SELECT P.CODIGO_BARRAS,I.NOMBRE AS INDUSTRIA,L.NOMBRE AS LINEA,M.NOMBRE AS MARCA,UPPER(P.NOMBRE) AS P_NOMBRE,UPPER(P.PRESENTACION),P.CODIGO_BARRAS AS ABREBIATURA,P.UNIDADES_POR_CAJA,P.CONTENIDO,P.UNIDAD_MEDIDA,'PZ' AS UNIDAD_EMPAQUE,P.COSTO,P.COSTO_VENTA
FROM   PRODUCTO P,ALMACEN_PRODUCTO AP,MARCA M,LINEA L,INDUSTRIA I
WHERE  1=1
AND    P.MARCA_ID = M.ID
AND    M.LINEA_ID=L.ID
AND    M.INDUSTRIA_ID=I.ID
AND    P.ID = AP.PRODUCTO_ID
AND    AP.ALMACEN_ID=3
ORDER BY INDUSTRIA,LINEA,MARCA,P_NOMBRE,PRESENTACION,CODIGO_BARRAS;

SELECT CODIGO_BARRAS,INDUSTRIA,LINEA,MARCA,NOMBRE,PRESENTACION,ABREBIATURA,UNIDADES_X_CAJA,CONTENIDO,UNIDAD_MEDIDA,UNIDAD_EMPAQUE,COSTO,COSTO_VENTA 
FROM   PRODUCTO
ORDER BY INDUSTRIA,LINEA,MARCA,NOMBRE,PRESENTACION,CODIGO_BARRAS;
